package com.alipay.altershield.defender.framework.exe.dal.mapper;

import com.alipay.altershield.defender.framework.exe.dal.dataobject.OpsCloudExeDefenderDetectDO;
import com.alipay.altershield.defender.framework.exe.dal.dataobject.OpsCloudExeDefenderDetectParam;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

/**
 * This class was generated by Ali-Generator
 * @author yhaoxuan
 */
@Mapper
public interface OpsCloudExeDefenderDetectMapper {

    /**
     * COUNT based on WHERE condition
     *
     * @param opsCloudExeDefenderDetectParam
     * @return
     *
     * @mbg.generated
     */
    long countByParam(OpsCloudExeDefenderDetectParam opsCloudExeDefenderDetectParam);

    /**
     * Delete based on WHERE condition
     *
     * @param opsCloudExeDefenderDetectParam
     * @return
     *
     * @mbg.generated
     */
    int deleteByParam(OpsCloudExeDefenderDetectParam opsCloudExeDefenderDetectParam);

    /**
     * Delete based on primary key
     *
     * @param detectExeId
     * @return
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String detectExeId);

    /**
     * Insert a single record
     *
     * @param record
     * @return
     *
     * @mbg.generated
     */
    int insert(OpsCloudExeDefenderDetectDO record);

    /**
     * Selectively insert a single record based on a field
     *
     * @param record
     * @return
     *
     * @mbg.generated
     */
    int insertSelective(OpsCloudExeDefenderDetectDO record);

    /**
     * Query based on WHERE condition, return does not contain long text fields
     *
     * @param opsCloudExeDefenderDetectParam
     * @return
     *
     * @mbg.generated
     */
    List<OpsCloudExeDefenderDetectDO> selectByParam(OpsCloudExeDefenderDetectParam opsCloudExeDefenderDetectParam);

    /**
     * Query based on primary key
     *
     * @param detectExeId
     * @return
     *
     * @mbg.generated
     */
    OpsCloudExeDefenderDetectDO selectByPrimaryKey(String detectExeId);

    /**
     * Selective update based on WHERE condition
     *
     * @param record
     * @param opsCloudExeDefenderDetectParam
     * @return
     *
     * @mbg.generated
     */
    int updateByParamSelective(@Param("record") OpsCloudExeDefenderDetectDO record, @Param("opsCloudExeDefenderDetectParam") OpsCloudExeDefenderDetectParam opsCloudExeDefenderDetectParam);

    /**
     * Update based on WHERE conditions, do not update long text fields
     *
     * @param record
     * @param opsCloudExeDefenderDetectParam
     * @return
     *
     * @mbg.generated
     */
    int updateByParam(@Param("record") OpsCloudExeDefenderDetectDO record, @Param("opsCloudExeDefenderDetectParam") OpsCloudExeDefenderDetectParam opsCloudExeDefenderDetectParam);

    /**
     * Selective update based on primary key
     *
     * @param record
     * @return
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(OpsCloudExeDefenderDetectDO record);

    /**
     * Update by primary key
     *
     * @param record
     * @return
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(OpsCloudExeDefenderDetectDO record);

    /**
     * Insert in batch
     *
     * @param records
     * @return
     *
     * @mbg.generated
     */
    int batchInsert(List<OpsCloudExeDefenderDetectDO> records);

    /**
     * Update the row record based on the primary key id
     *
     * @param detectExeId detection execution id
     * @return entity
     */
    OpsCloudExeDefenderDetectDO selectByPrimaryKeyForUpdate(@Param("id") String detectExeId);

    /**
     * Batch update verification entities ignore status
     *
     * @param detectExeIds detection ids
     * @param ignored whether the detection result is ignored or not. Y=ignored，N=not ignored
     * @return update columns
     */
    int batchUpdateByIds(@Param("detectExeIds") List<String> detectExeIds, @Param("ignored") String ignored);
}
