package com.alipay.altershield.defender.framework.meta.dal.mapper;

import com.alipay.altershield.defender.framework.meta.dal.dataobject.MetaDefenderRuleDO;
import com.alipay.altershield.defender.framework.meta.dal.dataobject.MetaDefenderRuleParam;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

/**
 * This class was generated by Ali-Generator
 * @author fujinfei
 */
@Mapper
public interface MetaDefenderRuleMapper {

    /**
     * COUNT based on WHERE condition
     * @param opsCloudMetaDefenderRuleParam
     * @return
     *
     * @mbg.generated
     */
    long countByParam(MetaDefenderRuleParam opsCloudMetaDefenderRuleParam);

    /**
     * Delete based on WHERE condition
     * @param opsCloudMetaDefenderRuleParam
     * @return
     *
     * @mbg.generated
     */
    int deleteByParam(MetaDefenderRuleParam opsCloudMetaDefenderRuleParam);

    /**
     * Delete based on primary key
     * @param id
     * @return
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * Insert a single record
     * @param record
     * @return
     *
     * @mbg.generated
     */
    int insert(MetaDefenderRuleDO record);

    /**
     * Selectively insert a single record based on a field
     * @param record
     * @return
     *
     * @mbg.generated
     */
    int insertSelective(MetaDefenderRuleDO record);

    /**
     * Query based on WHERE condition, return does not contain long text fields
     * @param opsCloudMetaDefenderRuleParam
     * @return
     *
     * @mbg.generated
     */
    List<MetaDefenderRuleDO> selectByParam(MetaDefenderRuleParam opsCloudMetaDefenderRuleParam);

    /**
     * @return
     *
     * @wujiao.zyt
     */
    List<MetaDefenderRuleDO> selectAll();

    /**
     * Query based on primary key
     * @param id
     * @return
     *
     * @mbg.generated
     */
    MetaDefenderRuleDO selectByPrimaryKey(String id);

    /**
     * Selective update based on WHERE condition
     * @param record
     * @param opsCloudMetaDefenderRuleParam
     * @return
     *
     * @mbg.generated
     */
    int updateByParamSelective(@Param("record") MetaDefenderRuleDO record, @Param("opsCloudMetaDefenderRuleParam") MetaDefenderRuleParam opsCloudMetaDefenderRuleParam);

    /**
     * Update based on WHERE conditions, do not update long text fields
     * @param record
     * @param opsCloudMetaDefenderRuleParam
     * @return
     *
     * @mbg.generated
     */
    int updateByParam(@Param("record") MetaDefenderRuleDO record, @Param("opsCloudMetaDefenderRuleParam") MetaDefenderRuleParam opsCloudMetaDefenderRuleParam);

    /**
     * Selective update based on primary key
     * @param record
     * @return
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MetaDefenderRuleDO record);

    /**
     * Update based on primary key, do not update long text fields
     * @param record
     * @return
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MetaDefenderRuleDO record);

    /**
     * Batch insert
     * @param records
     * @return
     *
     * @mbg.generated
     */
    int batchInsert(List<MetaDefenderRuleDO> records);
}
