/*
 * MIT License
 *
 * Copyright (c) [2023]
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package com.alipay.altershield.defender.framework.meta.dal.mapper;

import com.alipay.altershield.defender.framework.meta.dal.dataobject.MetaDefenderRuleDO;
import com.alipay.altershield.defender.framework.meta.dal.dataobject.MetaDefenderRuleParam;
import java.util.List;
import org.apache.ibatis.annotations.Param;

/**
 * This class was generated by Ali-Generator
 * @author xiangyue
 */
public interface MetaDefenderRuleMapper {
    /**
     * @return
     *
     * @wujiao.zyt
     */
    List<MetaDefenderRuleDO> selectAll();
    /**
     * 根据WHERE条件COUNT
     * @param metaDefenderRuleParam
     * @return
     *
     * @mbg.generated
     */
    long countByParam(MetaDefenderRuleParam metaDefenderRuleParam);

    /**
     * 根据WHERE条件删除
     * @param metaDefenderRuleParam
     * @return
     *
     * @mbg.generated
     */
    int deleteByParam(MetaDefenderRuleParam metaDefenderRuleParam);

    /**
     * 根据主键删除
     * @param id
     * @return
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * 插入单条记录
     * @param record
     * @return
     *
     * @mbg.generated
     */
    int insert(MetaDefenderRuleDO record);

    /**
     * 根据字段选择性插入单条记录
     * @param record
     * @return
     *
     * @mbg.generated
     */
    int insertSelective(MetaDefenderRuleDO record);

    /**
     * 根据WHERE条件查询，返回不包含长文本字段
     * @param metaDefenderRuleParam
     * @return
     *
     * @mbg.generated
     */
    List<MetaDefenderRuleDO> selectByParam(MetaDefenderRuleParam metaDefenderRuleParam);

    /**
     * 根据主键查询
     * @param id
     * @return
     *
     * @mbg.generated
     */
    MetaDefenderRuleDO selectByPrimaryKey(String id);

    /**
     * 根据WHERE条件选择性更新
     * @param record
     * @param metaDefenderRuleParam
     * @return
     *
     * @mbg.generated
     */
    int updateByParamSelective(@Param("record") MetaDefenderRuleDO record, @Param("metaDefenderRuleParam") MetaDefenderRuleParam metaDefenderRuleParam);

    /**
     * 根据WHERE条件更新，不更新长文本字段
     * @param record
     * @param metaDefenderRuleParam
     * @return
     *
     * @mbg.generated
     */
    int updateByParam(@Param("record") MetaDefenderRuleDO record, @Param("metaDefenderRuleParam") MetaDefenderRuleParam metaDefenderRuleParam);

    /**
     * 根据主键选择性更新
     * @param record
     * @return
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MetaDefenderRuleDO record);

    /**
     * 根据主键更新，不更新长文本字段
     * @param record
     * @return
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MetaDefenderRuleDO record);

    /**
     * 批量插入
     * @param records
     * @return
     *
     * @mbg.generated
     */
    int batchInsert(List<MetaDefenderRuleDO> records);
}