/*
 * MIT License
 *
 * Copyright (c) [2023]
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package com.alipay.altershield.change.meta.dal.mapper;

import com.alipay.altershield.change.meta.dal.dataobject.MetaBaseChangeSceneDO;
import com.alipay.altershield.change.meta.dal.dataobject.MetaChangeSceneDO;
import com.alipay.altershield.change.meta.dal.dataobject.MetaChangeSceneQueryParam;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

/**
 * This class was generated by Ali-Generator
 *
 * @author yuanji
 */
@Mapper
public interface MetaChangeSceneMapper {

    /**
     * 根据主键删除
     *
     * @param id
     * @return
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * 根据changeSceneKey删除
     *
     * @param changeSceneKey
     * @return
     */
    int deleteByChangeSceneKey(String changeSceneKey);

    /**
     * 插入单条记录
     *
     * @param record
     * @return
     * @mbg.generated
     */
    int insert(MetaChangeSceneDO record);

    /**
     * 根据WHERE条件查询，返回不包含长文本字段
     *
     * @param metaChangeSceneParam
     * @return
     * @mbg.generated
     */
    List<MetaBaseChangeSceneDO> selectByParam(MetaChangeSceneQueryParam metaChangeSceneParam);

    /**
     * 根据WHERE条件查询，返回数量
     *
     * @param metaChangeSceneParam
     * @return
     * @mbg.generated
     */
    long selectByParamCount(MetaChangeSceneQueryParam metaChangeSceneParam);

    /**
     * 根据主键查询
     *
     * @param id
     * @return
     * @mbg.generated
     */
    MetaChangeSceneDO selectByPrimaryKey(String id);

    /**
     * 同时查出关联表
     *
     * @param id
     * @return
     */
    MetaChangeSceneDO selectWithStepByPrimaryKey(String id);

    /**
     * 根据主键更新，不更新长文本字段
     *
     * @param record
     * @return
     * @mbg.generated
     */
    int updateByPrimaryKey(MetaChangeSceneDO record);

    /**
     * 根据changeSceneKey查询
     *
     * @param changeSceneKey
     * @return
     * @mbg.generated
     */
    MetaChangeSceneDO selectByPrimaryChangeSceneKey(String changeSceneKey);

    /**
     * 根据主键更新，更新代G
     * @param id
     * @param generation
     * @return
     */
    int updateGeneration(@Param("id") String id, @Param("generation") String generation);

    /**
     * 获取场景主要信息
     *
     * @param
     * @return java.util.List<com.alipay.opscloud.change.meta.dal.dataobject.MetaChangeSceneDO>
     * @author gaofeng.pan
     * @date 2022/11/9 16:38
     **/
    List<MetaChangeSceneDO> querySceneMainInfo();

    /**
     * 根据changeSceneKey获取对象数据
     *
     * @param changeSceneKey
     * @return com.alipay.opscloud.change.meta.dal.dataobject.MetaChangeSceneDO
     * @author gaofeng.pan
     * @date 2022/11/10 10:45
     **/
    MetaChangeSceneDO getFullEntity(@Param("changeSceneKey") String changeSceneKey);
}