/*
 * MIT License
 *
 * Copyright (c) [2023]
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package com.alipay.altershield.change.meta.dal.mapper;

import com.alipay.altershield.change.meta.dal.dataobject.MetaChangeTypeDO;
import com.alipay.altershield.change.meta.dal.dataobject.MetaChangeTypeParam;
import java.util.List;
import org.apache.ibatis.annotations.Param;

/**
 * This class was generated by Ali-Generator
 * @author xiangyue
 */
public interface MetaChangeTypeMapper {

    /**
     * 插入单条记录
     * @param record
     * @return
     *
     * @mbg.generated
     */
    int insert(MetaChangeTypeDO record);


    /**
     * 根据WHERE条件查询，
     * @param
     * @return
     *
     * @mbg.generated
     */
    List<MetaChangeTypeDO> selectByParam(@Param("category") String category, @Param("type") String type, @Param("size") int size);

    /**
     * 根据type查詢
     * @param  category
     * @param type
     * @return
     *
     * @mbg.generated
     */
    MetaChangeTypeDO selectByType(@Param("category") String category, @Param("type") String type);


    /**
     * 根据type刪除
     * @param type
     * @return
     *
     * @mbg.generated
     */
    int deleteByType(@Param("category") String category, @Param("type") String type);
}