/*
 * MIT License
 *
 * Copyright (c) [2023]
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package com.alipay.altershield.change.meta.dal.mapper;

import com.alipay.altershield.change.meta.dal.dataobject.MetaChangeStepDO;
import com.alipay.altershield.change.meta.dal.dataobject.MetaChangeStepParam;
import java.util.List;
import org.apache.ibatis.annotations.Param;

/**
 * This class was generated by Ali-Generator
 * @author xiangyue
 */
public interface MetaChangeStepMapper {

    /**
     * 根据主键删除
     * @param id
     * @return
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);


    /**
     * 根据changeSceneKey删除
     * @param changeSceneKey
     * @return
     *
     * @mbg.generated
     */
    int deleteByChangeSceneKey(String changeSceneKey);

    /**
     * 插入单条记录
     * @param record
     * @return
     *
     * @mbg.generated
     */
    int insert(MetaChangeStepDO record);


    /**
     * 根据changeSceneKey查询
     * @param changeSceneKey
     * @return
     *
     * @mbg.generated
     */
    List<MetaChangeStepDO> selectByChangeSceneKey(String changeSceneKey);

    /**
     * 根据changeKey来查询
     * @param changeKey
     * @return
     */
    MetaChangeStepDO selectByChangeKey(String changeKey);


    /**
     * 根据主键查询
     * @param id
     * @return
     *
     * @mbg.generated
     */
    MetaChangeStepDO selectByPrimaryKey(String id);


    /**
     * 根据主键更新，不更新长文本字段
     * @param record
     * @return
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MetaChangeStepDO record);

    /**
     * 批量插入
     * @param records
     * @return
     *
     * @mbg.generated
     */
    int batchInsert(List<MetaChangeStepDO> records);

    /**
     * 根据changeKey查询指定type的数量
     * @param changeKey
     * @param type
     * @return
     */
    int selectCountByChangeKeyAndType(@Param("changeKey") String changeKey, @Param("stepType") String type);


    /**
     * 根据changeSceneKey查询指定type
     * @param changeSceneKey
     * @param type
     * @return
     */

    List<MetaChangeStepDO> selectChangeStepByChangeSceneKeyAndType(@Param("changeSceneKey") String changeSceneKey, @Param("stepType") String type);

    /**
     * 根据id批量更新step
     * @param stepList
     */
    int batchUpdate(List<MetaChangeStepDO> stepList);
}