/*
 * MIT License
 *
 * Copyright (c) [2023]
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package com.alipay.altershield.change.exe.dal.mapper;

import com.alipay.altershield.change.exe.dal.dataobject.ExeNodeDO;
import com.alipay.altershield.change.exe.dal.dataobject.ExeNodeParam;
import java.util.List;
import org.apache.ibatis.annotations.Param;

/**
 * This class was generated by Ali-Generator
 * @author xiangyue
 */
public interface ExeNodeMapper {
    /**
     * 根据WHERE条件COUNT
     * @param exeNodeParam
     * @return
     *
     * @mbg.generated
     */
    long countByParam(ExeNodeParam exeNodeParam);

    /**
     * 根据WHERE条件删除
     * @param exeNodeParam
     * @return
     *
     * @mbg.generated
     */
    int deleteByParam(ExeNodeParam exeNodeParam);

    /**
     * 根据主键删除
     * @param nodeExeId
     * @return
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String nodeExeId);

    /**
     * 插入单条记录
     * @param record
     * @return
     *
     * @mbg.generated
     */
    int insert(ExeNodeDO record);

    /**
     * 根据字段选择性插入单条记录
     * @param record
     * @return
     *
     * @mbg.generated
     */
    int insertSelective(ExeNodeDO record);

    /**
     * 根据WHERE条件查询，返回不包含长文本字段
     * @param exeNodeParam
     * @return
     *
     * @mbg.generated
     */
    List<ExeNodeDO> selectByParam(ExeNodeParam exeNodeParam);

    /**
     * 根据主键查询
     * @param nodeExeId
     * @return
     *
     * @mbg.generated
     */
    ExeNodeDO selectByPrimaryKey(String nodeExeId);

    /**
     * 根据WHERE条件选择性更新
     * @param record
     * @param exeNodeParam
     * @return
     *
     * @mbg.generated
     */
    int updateByParamSelective(@Param("record") ExeNodeDO record, @Param("exeNodeParam") ExeNodeParam exeNodeParam);

    /**
     * 根据WHERE条件更新，不更新长文本字段
     * @param record
     * @param exeNodeParam
     * @return
     *
     * @mbg.generated
     */
    int updateByParam(@Param("record") ExeNodeDO record, @Param("exeNodeParam") ExeNodeParam exeNodeParam);

    /**
     * 根据主键更新，不更新长文本字段
     * @param record
     * @return
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ExeNodeDO record);

    /**
     * 批量插入
     * @param records
     * @return
     *
     * @mbg.generated
     */
    int batchInsert(List<ExeNodeDO> records);

    /**
     * 获取一个带锁的node
     * @param nodeId
     * @return
     */
    ExeNodeDO lockById(String nodeId);

    /**
     * 根据orderId来查询所有的执行结点
     * @param orderId
     * @return
     *
     * @mbg.generated
     */
    List<ExeNodeDO> selectByOrderId(String orderId);

    /**
     * 根据orderId和nodeType查询
     * @param  uid
     * @param orderId
     * @param nodeType
     * @return
     */
    List<ExeNodeDO> selectByOrderIdAndType(@Param("uid") String uid, @Param("orderId") String orderId, @Param("nodeType") String nodeType, @Param("size") Integer size);

    /**
     * 根据主键更新，不更新长文本字段
     * @param record
     * @return
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithOldState(@Param("exeNode") ExeNodeDO record, @Param("oldStatus") List<String> oldStatus);

}