/*
 * MIT License
 *
 * Copyright (c) [2023]
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
/*
 * Copyright Notice: This software is developed by Ant Small and Micro Financial Services Group Co., Ltd. This software and
 *  all the relevant information, including but not limited to any signs, images, photographs, animations, text,
 *  interface design, audios and videos, and printed materials, are protected by copyright laws and other intellectual
 *  property laws and treaties.
 *
 * The use of this software shall abide by the laws and regulations as well as Software Installation License
 * Agreement/Software Use Agreement updated from time to time. Without authorization from Ant Small and Micro Financial
 *  Services Group Co., Ltd., no one may conduct the following actions:
 *
 *   1) reproduce, spread, present, set up a mirror of, upload, download this software;
 *
 *   2) reverse engineer, decompile the source code of this software or try to find the source code in any other ways;
 *
 *   3) modify, translate and adapt this software, or develop derivative products, works, and services based on this
 *    software;
 *
 *   4) distribute, lease, rent, sub-license, demise or transfer any rights in relation to this software, or authorize
 *    the reproduction of this software on other’s computers.
 */
package com.alipay.altershield.change.exe.dal.mapper;

import com.alipay.opscloud.change.exe.dal.dataobject.ExeNodeDO;
import com.alipay.opscloud.change.exe.dal.dataobject.ExeNodeParam;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

/**
 * This class was generated by Ali-Generator
 * @author yuanji
 */
@Mapper
public interface ExeNodeMapper {
    /**
     * 根据WHERE条件COUNT
     * @param exeNodeParam
     * @return
     *
     * @mbg.generated
     */
    long countByParam(ExeNodeParam exeNodeParam);


    /**
     * 根据主键删除
     * @param nodeExeId
     * @return
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String nodeExeId);

    /**
     * 插入单条记录
     * @param record
     * @return
     *
     * @mbg.generated
     */
    int insert(ExeNodeDO record);


    /**
     * 根据orderId来查询所有的执行结点
     * @param orderId
     * @return
     *
     * @mbg.generated
     */
    List<ExeNodeDO> selectByOrderId(String orderId);


    /**
     * 根据主键查询
     * @param nodeExeId
     * @return
     *
     * @mbg.generated
     */
    ExeNodeDO selectByPrimaryKey(String nodeExeId);


    /**
     * 根据主键更新，不更新长文本字段
     * @param record
     * @return
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ExeNodeDO record);



    /**
     * 根据主键更新，不更新长文本字段
     * @param record
     * @return
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithOldState(@Param("exeNode") ExeNodeDO record, @Param("oldStatus") List<String> oldStatus);

    /**
     * 根据orderId和nodeType查询
     * @param  uid
     * @param orderId
     * @param nodeType
     * @return
     */
    List<ExeNodeDO> selectByOrderIdAndType(@Param("uid") String uid, @Param("orderId") String orderId, @Param("nodeType") String nodeType, @Param("size") Integer size);

    /**
     * 获取一个带锁的node
     * @param nodeId
     * @return
     */
    ExeNodeDO lockById(String nodeId);
}