/*
 * MIT License
 *
 * Copyright (c) [2023]
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package com.alipay.altershield.change.exe.dal.dataobject;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * This class was generated by Ali-Generator
 * @author xiangyue
 */
public class ExeChangeOrderParam {
    /**
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     *
     * @mbg.generated
     */
    @Deprecated
    protected boolean distinct;

    /**
     *
     * @mbg.generated
     */
    protected boolean page;

    /**
     *
     * @mbg.generated
     */
    protected int pageIndex;

    /**
     *
     * @mbg.generated
     */
    protected int pageSize;

    /**
     *
     * @mbg.generated
     */
    protected int pageStart;

    /**
     *
     * @mbg.generated
     */
    protected String distinctSql;

    /**
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     *
     * @mbg.generated
     */
    public ExeChangeOrderParam() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * @param orderCondition
     * @param sortType
     * @return
     *
     * @mbg.generated
     */
    public ExeChangeOrderParam appendOrderByClause(OrderCondition orderCondition, SortType sortType) {
        if (null != orderByClause) {
            orderByClause = orderByClause + ", " + orderCondition.getColumnName() + " " + sortType.getValue();
        } else {
            orderByClause = orderCondition.getColumnName() + " " + sortType.getValue();
        }
        return this;
    }

    /**
     * @return
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * @param distinct
     *
     * @mbg.generated
     */
    @Deprecated
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * @return
     *
     * @mbg.generated
     */
    @Deprecated
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * @param page
     * @return
     *
     * @mbg.generated
     */
    public ExeChangeOrderParam setPage(boolean page) {
        this.page = page;
        return this;
    }

    /**
     * @return
     *
     * @mbg.generated
     */
    public boolean isPage() {
        return page;
    }

    /**
     * @return
     *
     * @mbg.generated
     */
    public int getPageIndex() {
        return pageIndex;
    }

    /**
     * @param pageSize
     * @return
     *
     * @mbg.generated
     */
    public ExeChangeOrderParam setPageSize(int pageSize) {
        this.pageSize = pageSize < 1 ? 10 : pageSize;
        this.pageIndex = pageStart < 1 ? 0 : (pageStart - 1) * this.pageSize;
        return this;
    }

    /**
     * @return
     *
     * @mbg.generated
     */
    public int getPageSize() {
        return pageSize;
    }

    /**
     * @param pageStart
     * @return
     *
     * @mbg.generated
     */
    public ExeChangeOrderParam setPageStart(int pageStart) {
        this.pageStart = pageStart < 1 ? 1 : pageStart;
        this.pageIndex = (this.pageStart - 1) * this.pageSize;
        return this;
    }

    /**
     * @return
     *
     * @mbg.generated
     */
    public int getPageStart() {
        return pageStart;
    }

    /**
     * @param pageStart
     * @param pageSize
     *
     * @mbg.generated
     */
    public void setPagination(int pageStart, int pageSize) {
        this.page = true;
        this.pageSize = pageSize < 1 ? 10 : pageSize;
        this.pageIndex = pageStart < 1 ? 0 : (pageStart - 1) * this.pageSize;
    }

    /**
     * @param condition
     * @return
     *
     * @mbg.generated
     */
    public ExeChangeOrderParam appendDistinct(OrderCondition condition) {
        if (null != distinctSql){
            distinctSql = distinctSql + ", " + condition.getColumnName();
        } else {
            distinctSql = condition.getColumnName();
        }
        return this;
    }

    /**
     * @return
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * @param criteria
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * @return
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * @return
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * @return
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     *
     * @mbg.generated
     */
    protected abstract static class AbstractGeneratedCriteria {
        protected List<Criterion> criteria;

        protected AbstractGeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andOrderIdIsNull() {
            addCriterion("order_id is null");
            return (Criteria) this;
        }

        public Criteria andOrderIdIsNotNull() {
            addCriterion("order_id is not null");
            return (Criteria) this;
        }

        public Criteria andOrderIdEqualTo(String value) {
            addCriterion("order_id =", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotEqualTo(String value) {
            addCriterion("order_id <>", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThan(String value) {
            addCriterion("order_id >", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThanOrEqualTo(String value) {
            addCriterion("order_id >=", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThan(String value) {
            addCriterion("order_id <", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThanOrEqualTo(String value) {
            addCriterion("order_id <=", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLike(String value) {
            addCriterion("order_id like", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotLike(String value) {
            addCriterion("order_id not like", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdIn(List<String> values) {
            addCriterion("order_id in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotIn(List<String> values) {
            addCriterion("order_id not in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdBetween(String value1, String value2) {
            addCriterion("order_id between", value1, value2, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotBetween(String value1, String value2) {
            addCriterion("order_id not between", value1, value2, "orderId");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIsNull() {
            addCriterion("gmt_create is null");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIsNotNull() {
            addCriterion("gmt_create is not null");
            return (Criteria) this;
        }

        public Criteria andGmtCreateEqualTo(Date value) {
            addCriterion("gmt_create =", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotEqualTo(Date value) {
            addCriterion("gmt_create <>", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateGreaterThan(Date value) {
            addCriterion("gmt_create >", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateGreaterThanOrEqualTo(Date value) {
            addCriterion("gmt_create >=", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateLessThan(Date value) {
            addCriterion("gmt_create <", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateLessThanOrEqualTo(Date value) {
            addCriterion("gmt_create <=", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIn(List<Date> values) {
            addCriterion("gmt_create in", values, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotIn(List<Date> values) {
            addCriterion("gmt_create not in", values, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateBetween(Date value1, Date value2) {
            addCriterion("gmt_create between", value1, value2, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotBetween(Date value1, Date value2) {
            addCriterion("gmt_create not between", value1, value2, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIsNull() {
            addCriterion("gmt_modified is null");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIsNotNull() {
            addCriterion("gmt_modified is not null");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedEqualTo(Date value) {
            addCriterion("gmt_modified =", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotEqualTo(Date value) {
            addCriterion("gmt_modified <>", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedGreaterThan(Date value) {
            addCriterion("gmt_modified >", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedGreaterThanOrEqualTo(Date value) {
            addCriterion("gmt_modified >=", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedLessThan(Date value) {
            addCriterion("gmt_modified <", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedLessThanOrEqualTo(Date value) {
            addCriterion("gmt_modified <=", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIn(List<Date> values) {
            addCriterion("gmt_modified in", values, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotIn(List<Date> values) {
            addCriterion("gmt_modified not in", values, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedBetween(Date value1, Date value2) {
            addCriterion("gmt_modified between", value1, value2, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotBetween(Date value1, Date value2) {
            addCriterion("gmt_modified not between", value1, value2, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andBizExecOrderIdIsNull() {
            addCriterion("biz_exec_order_id is null");
            return (Criteria) this;
        }

        public Criteria andBizExecOrderIdIsNotNull() {
            addCriterion("biz_exec_order_id is not null");
            return (Criteria) this;
        }

        public Criteria andBizExecOrderIdEqualTo(String value) {
            addCriterion("biz_exec_order_id =", value, "bizExecOrderId");
            return (Criteria) this;
        }

        public Criteria andBizExecOrderIdNotEqualTo(String value) {
            addCriterion("biz_exec_order_id <>", value, "bizExecOrderId");
            return (Criteria) this;
        }

        public Criteria andBizExecOrderIdGreaterThan(String value) {
            addCriterion("biz_exec_order_id >", value, "bizExecOrderId");
            return (Criteria) this;
        }

        public Criteria andBizExecOrderIdGreaterThanOrEqualTo(String value) {
            addCriterion("biz_exec_order_id >=", value, "bizExecOrderId");
            return (Criteria) this;
        }

        public Criteria andBizExecOrderIdLessThan(String value) {
            addCriterion("biz_exec_order_id <", value, "bizExecOrderId");
            return (Criteria) this;
        }

        public Criteria andBizExecOrderIdLessThanOrEqualTo(String value) {
            addCriterion("biz_exec_order_id <=", value, "bizExecOrderId");
            return (Criteria) this;
        }

        public Criteria andBizExecOrderIdLike(String value) {
            addCriterion("biz_exec_order_id like", value, "bizExecOrderId");
            return (Criteria) this;
        }

        public Criteria andBizExecOrderIdNotLike(String value) {
            addCriterion("biz_exec_order_id not like", value, "bizExecOrderId");
            return (Criteria) this;
        }

        public Criteria andBizExecOrderIdIn(List<String> values) {
            addCriterion("biz_exec_order_id in", values, "bizExecOrderId");
            return (Criteria) this;
        }

        public Criteria andBizExecOrderIdNotIn(List<String> values) {
            addCriterion("biz_exec_order_id not in", values, "bizExecOrderId");
            return (Criteria) this;
        }

        public Criteria andBizExecOrderIdBetween(String value1, String value2) {
            addCriterion("biz_exec_order_id between", value1, value2, "bizExecOrderId");
            return (Criteria) this;
        }

        public Criteria andBizExecOrderIdNotBetween(String value1, String value2) {
            addCriterion("biz_exec_order_id not between", value1, value2, "bizExecOrderId");
            return (Criteria) this;
        }

        public Criteria andChangeSceneKeyIsNull() {
            addCriterion("change_scene_key is null");
            return (Criteria) this;
        }

        public Criteria andChangeSceneKeyIsNotNull() {
            addCriterion("change_scene_key is not null");
            return (Criteria) this;
        }

        public Criteria andChangeSceneKeyEqualTo(String value) {
            addCriterion("change_scene_key =", value, "changeSceneKey");
            return (Criteria) this;
        }

        public Criteria andChangeSceneKeyNotEqualTo(String value) {
            addCriterion("change_scene_key <>", value, "changeSceneKey");
            return (Criteria) this;
        }

        public Criteria andChangeSceneKeyGreaterThan(String value) {
            addCriterion("change_scene_key >", value, "changeSceneKey");
            return (Criteria) this;
        }

        public Criteria andChangeSceneKeyGreaterThanOrEqualTo(String value) {
            addCriterion("change_scene_key >=", value, "changeSceneKey");
            return (Criteria) this;
        }

        public Criteria andChangeSceneKeyLessThan(String value) {
            addCriterion("change_scene_key <", value, "changeSceneKey");
            return (Criteria) this;
        }

        public Criteria andChangeSceneKeyLessThanOrEqualTo(String value) {
            addCriterion("change_scene_key <=", value, "changeSceneKey");
            return (Criteria) this;
        }

        public Criteria andChangeSceneKeyLike(String value) {
            addCriterion("change_scene_key like", value, "changeSceneKey");
            return (Criteria) this;
        }

        public Criteria andChangeSceneKeyNotLike(String value) {
            addCriterion("change_scene_key not like", value, "changeSceneKey");
            return (Criteria) this;
        }

        public Criteria andChangeSceneKeyIn(List<String> values) {
            addCriterion("change_scene_key in", values, "changeSceneKey");
            return (Criteria) this;
        }

        public Criteria andChangeSceneKeyNotIn(List<String> values) {
            addCriterion("change_scene_key not in", values, "changeSceneKey");
            return (Criteria) this;
        }

        public Criteria andChangeSceneKeyBetween(String value1, String value2) {
            addCriterion("change_scene_key between", value1, value2, "changeSceneKey");
            return (Criteria) this;
        }

        public Criteria andChangeSceneKeyNotBetween(String value1, String value2) {
            addCriterion("change_scene_key not between", value1, value2, "changeSceneKey");
            return (Criteria) this;
        }

        public Criteria andPlatformIsNull() {
            addCriterion("platform is null");
            return (Criteria) this;
        }

        public Criteria andPlatformIsNotNull() {
            addCriterion("platform is not null");
            return (Criteria) this;
        }

        public Criteria andPlatformEqualTo(String value) {
            addCriterion("platform =", value, "platform");
            return (Criteria) this;
        }

        public Criteria andPlatformNotEqualTo(String value) {
            addCriterion("platform <>", value, "platform");
            return (Criteria) this;
        }

        public Criteria andPlatformGreaterThan(String value) {
            addCriterion("platform >", value, "platform");
            return (Criteria) this;
        }

        public Criteria andPlatformGreaterThanOrEqualTo(String value) {
            addCriterion("platform >=", value, "platform");
            return (Criteria) this;
        }

        public Criteria andPlatformLessThan(String value) {
            addCriterion("platform <", value, "platform");
            return (Criteria) this;
        }

        public Criteria andPlatformLessThanOrEqualTo(String value) {
            addCriterion("platform <=", value, "platform");
            return (Criteria) this;
        }

        public Criteria andPlatformLike(String value) {
            addCriterion("platform like", value, "platform");
            return (Criteria) this;
        }

        public Criteria andPlatformNotLike(String value) {
            addCriterion("platform not like", value, "platform");
            return (Criteria) this;
        }

        public Criteria andPlatformIn(List<String> values) {
            addCriterion("platform in", values, "platform");
            return (Criteria) this;
        }

        public Criteria andPlatformNotIn(List<String> values) {
            addCriterion("platform not in", values, "platform");
            return (Criteria) this;
        }

        public Criteria andPlatformBetween(String value1, String value2) {
            addCriterion("platform between", value1, value2, "platform");
            return (Criteria) this;
        }

        public Criteria andPlatformNotBetween(String value1, String value2) {
            addCriterion("platform not between", value1, value2, "platform");
            return (Criteria) this;
        }

        public Criteria andTraceIdIsNull() {
            addCriterion("trace_id is null");
            return (Criteria) this;
        }

        public Criteria andTraceIdIsNotNull() {
            addCriterion("trace_id is not null");
            return (Criteria) this;
        }

        public Criteria andTraceIdEqualTo(String value) {
            addCriterion("trace_id =", value, "traceId");
            return (Criteria) this;
        }

        public Criteria andTraceIdNotEqualTo(String value) {
            addCriterion("trace_id <>", value, "traceId");
            return (Criteria) this;
        }

        public Criteria andTraceIdGreaterThan(String value) {
            addCriterion("trace_id >", value, "traceId");
            return (Criteria) this;
        }

        public Criteria andTraceIdGreaterThanOrEqualTo(String value) {
            addCriterion("trace_id >=", value, "traceId");
            return (Criteria) this;
        }

        public Criteria andTraceIdLessThan(String value) {
            addCriterion("trace_id <", value, "traceId");
            return (Criteria) this;
        }

        public Criteria andTraceIdLessThanOrEqualTo(String value) {
            addCriterion("trace_id <=", value, "traceId");
            return (Criteria) this;
        }

        public Criteria andTraceIdLike(String value) {
            addCriterion("trace_id like", value, "traceId");
            return (Criteria) this;
        }

        public Criteria andTraceIdNotLike(String value) {
            addCriterion("trace_id not like", value, "traceId");
            return (Criteria) this;
        }

        public Criteria andTraceIdIn(List<String> values) {
            addCriterion("trace_id in", values, "traceId");
            return (Criteria) this;
        }

        public Criteria andTraceIdNotIn(List<String> values) {
            addCriterion("trace_id not in", values, "traceId");
            return (Criteria) this;
        }

        public Criteria andTraceIdBetween(String value1, String value2) {
            addCriterion("trace_id between", value1, value2, "traceId");
            return (Criteria) this;
        }

        public Criteria andTraceIdNotBetween(String value1, String value2) {
            addCriterion("trace_id not between", value1, value2, "traceId");
            return (Criteria) this;
        }

        public Criteria andUidIsNull() {
            addCriterion("uid is null");
            return (Criteria) this;
        }

        public Criteria andUidIsNotNull() {
            addCriterion("uid is not null");
            return (Criteria) this;
        }

        public Criteria andUidEqualTo(String value) {
            addCriterion("uid =", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotEqualTo(String value) {
            addCriterion("uid <>", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidGreaterThan(String value) {
            addCriterion("uid >", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidGreaterThanOrEqualTo(String value) {
            addCriterion("uid >=", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLessThan(String value) {
            addCriterion("uid <", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLessThanOrEqualTo(String value) {
            addCriterion("uid <=", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLike(String value) {
            addCriterion("uid like", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotLike(String value) {
            addCriterion("uid not like", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidIn(List<String> values) {
            addCriterion("uid in", values, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotIn(List<String> values) {
            addCriterion("uid not in", values, "uid");
            return (Criteria) this;
        }

        public Criteria andUidBetween(String value1, String value2) {
            addCriterion("uid between", value1, value2, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotBetween(String value1, String value2) {
            addCriterion("uid not between", value1, value2, "uid");
            return (Criteria) this;
        }

        public Criteria andCoordIsNull() {
            addCriterion("coord is null");
            return (Criteria) this;
        }

        public Criteria andCoordIsNotNull() {
            addCriterion("coord is not null");
            return (Criteria) this;
        }

        public Criteria andCoordEqualTo(String value) {
            addCriterion("coord =", value, "coord");
            return (Criteria) this;
        }

        public Criteria andCoordNotEqualTo(String value) {
            addCriterion("coord <>", value, "coord");
            return (Criteria) this;
        }

        public Criteria andCoordGreaterThan(String value) {
            addCriterion("coord >", value, "coord");
            return (Criteria) this;
        }

        public Criteria andCoordGreaterThanOrEqualTo(String value) {
            addCriterion("coord >=", value, "coord");
            return (Criteria) this;
        }

        public Criteria andCoordLessThan(String value) {
            addCriterion("coord <", value, "coord");
            return (Criteria) this;
        }

        public Criteria andCoordLessThanOrEqualTo(String value) {
            addCriterion("coord <=", value, "coord");
            return (Criteria) this;
        }

        public Criteria andCoordLike(String value) {
            addCriterion("coord like", value, "coord");
            return (Criteria) this;
        }

        public Criteria andCoordNotLike(String value) {
            addCriterion("coord not like", value, "coord");
            return (Criteria) this;
        }

        public Criteria andCoordIn(List<String> values) {
            addCriterion("coord in", values, "coord");
            return (Criteria) this;
        }

        public Criteria andCoordNotIn(List<String> values) {
            addCriterion("coord not in", values, "coord");
            return (Criteria) this;
        }

        public Criteria andCoordBetween(String value1, String value2) {
            addCriterion("coord between", value1, value2, "coord");
            return (Criteria) this;
        }

        public Criteria andCoordNotBetween(String value1, String value2) {
            addCriterion("coord not between", value1, value2, "coord");
            return (Criteria) this;
        }

        public Criteria andChangeTitleIsNull() {
            addCriterion("change_title is null");
            return (Criteria) this;
        }

        public Criteria andChangeTitleIsNotNull() {
            addCriterion("change_title is not null");
            return (Criteria) this;
        }

        public Criteria andChangeTitleEqualTo(String value) {
            addCriterion("change_title =", value, "changeTitle");
            return (Criteria) this;
        }

        public Criteria andChangeTitleNotEqualTo(String value) {
            addCriterion("change_title <>", value, "changeTitle");
            return (Criteria) this;
        }

        public Criteria andChangeTitleGreaterThan(String value) {
            addCriterion("change_title >", value, "changeTitle");
            return (Criteria) this;
        }

        public Criteria andChangeTitleGreaterThanOrEqualTo(String value) {
            addCriterion("change_title >=", value, "changeTitle");
            return (Criteria) this;
        }

        public Criteria andChangeTitleLessThan(String value) {
            addCriterion("change_title <", value, "changeTitle");
            return (Criteria) this;
        }

        public Criteria andChangeTitleLessThanOrEqualTo(String value) {
            addCriterion("change_title <=", value, "changeTitle");
            return (Criteria) this;
        }

        public Criteria andChangeTitleLike(String value) {
            addCriterion("change_title like", value, "changeTitle");
            return (Criteria) this;
        }

        public Criteria andChangeTitleNotLike(String value) {
            addCriterion("change_title not like", value, "changeTitle");
            return (Criteria) this;
        }

        public Criteria andChangeTitleIn(List<String> values) {
            addCriterion("change_title in", values, "changeTitle");
            return (Criteria) this;
        }

        public Criteria andChangeTitleNotIn(List<String> values) {
            addCriterion("change_title not in", values, "changeTitle");
            return (Criteria) this;
        }

        public Criteria andChangeTitleBetween(String value1, String value2) {
            addCriterion("change_title between", value1, value2, "changeTitle");
            return (Criteria) this;
        }

        public Criteria andChangeTitleNotBetween(String value1, String value2) {
            addCriterion("change_title not between", value1, value2, "changeTitle");
            return (Criteria) this;
        }

        public Criteria andChangeUrlIsNull() {
            addCriterion("change_url is null");
            return (Criteria) this;
        }

        public Criteria andChangeUrlIsNotNull() {
            addCriterion("change_url is not null");
            return (Criteria) this;
        }

        public Criteria andChangeUrlEqualTo(String value) {
            addCriterion("change_url =", value, "changeUrl");
            return (Criteria) this;
        }

        public Criteria andChangeUrlNotEqualTo(String value) {
            addCriterion("change_url <>", value, "changeUrl");
            return (Criteria) this;
        }

        public Criteria andChangeUrlGreaterThan(String value) {
            addCriterion("change_url >", value, "changeUrl");
            return (Criteria) this;
        }

        public Criteria andChangeUrlGreaterThanOrEqualTo(String value) {
            addCriterion("change_url >=", value, "changeUrl");
            return (Criteria) this;
        }

        public Criteria andChangeUrlLessThan(String value) {
            addCriterion("change_url <", value, "changeUrl");
            return (Criteria) this;
        }

        public Criteria andChangeUrlLessThanOrEqualTo(String value) {
            addCriterion("change_url <=", value, "changeUrl");
            return (Criteria) this;
        }

        public Criteria andChangeUrlLike(String value) {
            addCriterion("change_url like", value, "changeUrl");
            return (Criteria) this;
        }

        public Criteria andChangeUrlNotLike(String value) {
            addCriterion("change_url not like", value, "changeUrl");
            return (Criteria) this;
        }

        public Criteria andChangeUrlIn(List<String> values) {
            addCriterion("change_url in", values, "changeUrl");
            return (Criteria) this;
        }

        public Criteria andChangeUrlNotIn(List<String> values) {
            addCriterion("change_url not in", values, "changeUrl");
            return (Criteria) this;
        }

        public Criteria andChangeUrlBetween(String value1, String value2) {
            addCriterion("change_url between", value1, value2, "changeUrl");
            return (Criteria) this;
        }

        public Criteria andChangeUrlNotBetween(String value1, String value2) {
            addCriterion("change_url not between", value1, value2, "changeUrl");
            return (Criteria) this;
        }

        public Criteria andChangeScenarioCodeIsNull() {
            addCriterion("change_scenario_code is null");
            return (Criteria) this;
        }

        public Criteria andChangeScenarioCodeIsNotNull() {
            addCriterion("change_scenario_code is not null");
            return (Criteria) this;
        }

        public Criteria andChangeScenarioCodeEqualTo(String value) {
            addCriterion("change_scenario_code =", value, "changeScenarioCode");
            return (Criteria) this;
        }

        public Criteria andChangeScenarioCodeNotEqualTo(String value) {
            addCriterion("change_scenario_code <>", value, "changeScenarioCode");
            return (Criteria) this;
        }

        public Criteria andChangeScenarioCodeGreaterThan(String value) {
            addCriterion("change_scenario_code >", value, "changeScenarioCode");
            return (Criteria) this;
        }

        public Criteria andChangeScenarioCodeGreaterThanOrEqualTo(String value) {
            addCriterion("change_scenario_code >=", value, "changeScenarioCode");
            return (Criteria) this;
        }

        public Criteria andChangeScenarioCodeLessThan(String value) {
            addCriterion("change_scenario_code <", value, "changeScenarioCode");
            return (Criteria) this;
        }

        public Criteria andChangeScenarioCodeLessThanOrEqualTo(String value) {
            addCriterion("change_scenario_code <=", value, "changeScenarioCode");
            return (Criteria) this;
        }

        public Criteria andChangeScenarioCodeLike(String value) {
            addCriterion("change_scenario_code like", value, "changeScenarioCode");
            return (Criteria) this;
        }

        public Criteria andChangeScenarioCodeNotLike(String value) {
            addCriterion("change_scenario_code not like", value, "changeScenarioCode");
            return (Criteria) this;
        }

        public Criteria andChangeScenarioCodeIn(List<String> values) {
            addCriterion("change_scenario_code in", values, "changeScenarioCode");
            return (Criteria) this;
        }

        public Criteria andChangeScenarioCodeNotIn(List<String> values) {
            addCriterion("change_scenario_code not in", values, "changeScenarioCode");
            return (Criteria) this;
        }

        public Criteria andChangeScenarioCodeBetween(String value1, String value2) {
            addCriterion("change_scenario_code between", value1, value2, "changeScenarioCode");
            return (Criteria) this;
        }

        public Criteria andChangeScenarioCodeNotBetween(String value1, String value2) {
            addCriterion("change_scenario_code not between", value1, value2, "changeScenarioCode");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("status like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("status not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNull() {
            addCriterion("creator is null");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNotNull() {
            addCriterion("creator is not null");
            return (Criteria) this;
        }

        public Criteria andCreatorEqualTo(String value) {
            addCriterion("creator =", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotEqualTo(String value) {
            addCriterion("creator <>", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThan(String value) {
            addCriterion("creator >", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThanOrEqualTo(String value) {
            addCriterion("creator >=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThan(String value) {
            addCriterion("creator <", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThanOrEqualTo(String value) {
            addCriterion("creator <=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLike(String value) {
            addCriterion("creator like", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotLike(String value) {
            addCriterion("creator not like", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorIn(List<String> values) {
            addCriterion("creator in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotIn(List<String> values) {
            addCriterion("creator not in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorBetween(String value1, String value2) {
            addCriterion("creator between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotBetween(String value1, String value2) {
            addCriterion("creator not between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andExecutorIsNull() {
            addCriterion("executor is null");
            return (Criteria) this;
        }

        public Criteria andExecutorIsNotNull() {
            addCriterion("executor is not null");
            return (Criteria) this;
        }

        public Criteria andExecutorEqualTo(String value) {
            addCriterion("executor =", value, "executor");
            return (Criteria) this;
        }

        public Criteria andExecutorNotEqualTo(String value) {
            addCriterion("executor <>", value, "executor");
            return (Criteria) this;
        }

        public Criteria andExecutorGreaterThan(String value) {
            addCriterion("executor >", value, "executor");
            return (Criteria) this;
        }

        public Criteria andExecutorGreaterThanOrEqualTo(String value) {
            addCriterion("executor >=", value, "executor");
            return (Criteria) this;
        }

        public Criteria andExecutorLessThan(String value) {
            addCriterion("executor <", value, "executor");
            return (Criteria) this;
        }

        public Criteria andExecutorLessThanOrEqualTo(String value) {
            addCriterion("executor <=", value, "executor");
            return (Criteria) this;
        }

        public Criteria andExecutorLike(String value) {
            addCriterion("executor like", value, "executor");
            return (Criteria) this;
        }

        public Criteria andExecutorNotLike(String value) {
            addCriterion("executor not like", value, "executor");
            return (Criteria) this;
        }

        public Criteria andExecutorIn(List<String> values) {
            addCriterion("executor in", values, "executor");
            return (Criteria) this;
        }

        public Criteria andExecutorNotIn(List<String> values) {
            addCriterion("executor not in", values, "executor");
            return (Criteria) this;
        }

        public Criteria andExecutorBetween(String value1, String value2) {
            addCriterion("executor between", value1, value2, "executor");
            return (Criteria) this;
        }

        public Criteria andExecutorNotBetween(String value1, String value2) {
            addCriterion("executor not between", value1, value2, "executor");
            return (Criteria) this;
        }

        public Criteria andChangePhasesIsNull() {
            addCriterion("change_phases is null");
            return (Criteria) this;
        }

        public Criteria andChangePhasesIsNotNull() {
            addCriterion("change_phases is not null");
            return (Criteria) this;
        }

        public Criteria andChangePhasesEqualTo(String value) {
            addCriterion("change_phases =", value, "changePhases");
            return (Criteria) this;
        }

        public Criteria andChangePhasesNotEqualTo(String value) {
            addCriterion("change_phases <>", value, "changePhases");
            return (Criteria) this;
        }

        public Criteria andChangePhasesGreaterThan(String value) {
            addCriterion("change_phases >", value, "changePhases");
            return (Criteria) this;
        }

        public Criteria andChangePhasesGreaterThanOrEqualTo(String value) {
            addCriterion("change_phases >=", value, "changePhases");
            return (Criteria) this;
        }

        public Criteria andChangePhasesLessThan(String value) {
            addCriterion("change_phases <", value, "changePhases");
            return (Criteria) this;
        }

        public Criteria andChangePhasesLessThanOrEqualTo(String value) {
            addCriterion("change_phases <=", value, "changePhases");
            return (Criteria) this;
        }

        public Criteria andChangePhasesLike(String value) {
            addCriterion("change_phases like", value, "changePhases");
            return (Criteria) this;
        }

        public Criteria andChangePhasesNotLike(String value) {
            addCriterion("change_phases not like", value, "changePhases");
            return (Criteria) this;
        }

        public Criteria andChangePhasesIn(List<String> values) {
            addCriterion("change_phases in", values, "changePhases");
            return (Criteria) this;
        }

        public Criteria andChangePhasesNotIn(List<String> values) {
            addCriterion("change_phases not in", values, "changePhases");
            return (Criteria) this;
        }

        public Criteria andChangePhasesBetween(String value1, String value2) {
            addCriterion("change_phases between", value1, value2, "changePhases");
            return (Criteria) this;
        }

        public Criteria andChangePhasesNotBetween(String value1, String value2) {
            addCriterion("change_phases not between", value1, value2, "changePhases");
            return (Criteria) this;
        }

        public Criteria andMsgIsNull() {
            addCriterion("msg is null");
            return (Criteria) this;
        }

        public Criteria andMsgIsNotNull() {
            addCriterion("msg is not null");
            return (Criteria) this;
        }

        public Criteria andMsgEqualTo(String value) {
            addCriterion("msg =", value, "msg");
            return (Criteria) this;
        }

        public Criteria andMsgNotEqualTo(String value) {
            addCriterion("msg <>", value, "msg");
            return (Criteria) this;
        }

        public Criteria andMsgGreaterThan(String value) {
            addCriterion("msg >", value, "msg");
            return (Criteria) this;
        }

        public Criteria andMsgGreaterThanOrEqualTo(String value) {
            addCriterion("msg >=", value, "msg");
            return (Criteria) this;
        }

        public Criteria andMsgLessThan(String value) {
            addCriterion("msg <", value, "msg");
            return (Criteria) this;
        }

        public Criteria andMsgLessThanOrEqualTo(String value) {
            addCriterion("msg <=", value, "msg");
            return (Criteria) this;
        }

        public Criteria andMsgLike(String value) {
            addCriterion("msg like", value, "msg");
            return (Criteria) this;
        }

        public Criteria andMsgNotLike(String value) {
            addCriterion("msg not like", value, "msg");
            return (Criteria) this;
        }

        public Criteria andMsgIn(List<String> values) {
            addCriterion("msg in", values, "msg");
            return (Criteria) this;
        }

        public Criteria andMsgNotIn(List<String> values) {
            addCriterion("msg not in", values, "msg");
            return (Criteria) this;
        }

        public Criteria andMsgBetween(String value1, String value2) {
            addCriterion("msg between", value1, value2, "msg");
            return (Criteria) this;
        }

        public Criteria andMsgNotBetween(String value1, String value2) {
            addCriterion("msg not between", value1, value2, "msg");
            return (Criteria) this;
        }

        public Criteria andTenantCodeIsNull() {
            addCriterion("tenant_code is null");
            return (Criteria) this;
        }

        public Criteria andTenantCodeIsNotNull() {
            addCriterion("tenant_code is not null");
            return (Criteria) this;
        }

        public Criteria andTenantCodeEqualTo(String value) {
            addCriterion("tenant_code =", value, "tenantCode");
            return (Criteria) this;
        }

        public Criteria andTenantCodeNotEqualTo(String value) {
            addCriterion("tenant_code <>", value, "tenantCode");
            return (Criteria) this;
        }

        public Criteria andTenantCodeGreaterThan(String value) {
            addCriterion("tenant_code >", value, "tenantCode");
            return (Criteria) this;
        }

        public Criteria andTenantCodeGreaterThanOrEqualTo(String value) {
            addCriterion("tenant_code >=", value, "tenantCode");
            return (Criteria) this;
        }

        public Criteria andTenantCodeLessThan(String value) {
            addCriterion("tenant_code <", value, "tenantCode");
            return (Criteria) this;
        }

        public Criteria andTenantCodeLessThanOrEqualTo(String value) {
            addCriterion("tenant_code <=", value, "tenantCode");
            return (Criteria) this;
        }

        public Criteria andTenantCodeLike(String value) {
            addCriterion("tenant_code like", value, "tenantCode");
            return (Criteria) this;
        }

        public Criteria andTenantCodeNotLike(String value) {
            addCriterion("tenant_code not like", value, "tenantCode");
            return (Criteria) this;
        }

        public Criteria andTenantCodeIn(List<String> values) {
            addCriterion("tenant_code in", values, "tenantCode");
            return (Criteria) this;
        }

        public Criteria andTenantCodeNotIn(List<String> values) {
            addCriterion("tenant_code not in", values, "tenantCode");
            return (Criteria) this;
        }

        public Criteria andTenantCodeBetween(String value1, String value2) {
            addCriterion("tenant_code between", value1, value2, "tenantCode");
            return (Criteria) this;
        }

        public Criteria andTenantCodeNotBetween(String value1, String value2) {
            addCriterion("tenant_code not between", value1, value2, "tenantCode");
            return (Criteria) this;
        }

        public Criteria andFromCloudIdIsNull() {
            addCriterion("from_cloud_id is null");
            return (Criteria) this;
        }

        public Criteria andFromCloudIdIsNotNull() {
            addCriterion("from_cloud_id is not null");
            return (Criteria) this;
        }

        public Criteria andFromCloudIdEqualTo(String value) {
            addCriterion("from_cloud_id =", value, "fromCloudId");
            return (Criteria) this;
        }

        public Criteria andFromCloudIdNotEqualTo(String value) {
            addCriterion("from_cloud_id <>", value, "fromCloudId");
            return (Criteria) this;
        }

        public Criteria andFromCloudIdGreaterThan(String value) {
            addCriterion("from_cloud_id >", value, "fromCloudId");
            return (Criteria) this;
        }

        public Criteria andFromCloudIdGreaterThanOrEqualTo(String value) {
            addCriterion("from_cloud_id >=", value, "fromCloudId");
            return (Criteria) this;
        }

        public Criteria andFromCloudIdLessThan(String value) {
            addCriterion("from_cloud_id <", value, "fromCloudId");
            return (Criteria) this;
        }

        public Criteria andFromCloudIdLessThanOrEqualTo(String value) {
            addCriterion("from_cloud_id <=", value, "fromCloudId");
            return (Criteria) this;
        }

        public Criteria andFromCloudIdLike(String value) {
            addCriterion("from_cloud_id like", value, "fromCloudId");
            return (Criteria) this;
        }

        public Criteria andFromCloudIdNotLike(String value) {
            addCriterion("from_cloud_id not like", value, "fromCloudId");
            return (Criteria) this;
        }

        public Criteria andFromCloudIdIn(List<String> values) {
            addCriterion("from_cloud_id in", values, "fromCloudId");
            return (Criteria) this;
        }

        public Criteria andFromCloudIdNotIn(List<String> values) {
            addCriterion("from_cloud_id not in", values, "fromCloudId");
            return (Criteria) this;
        }

        public Criteria andFromCloudIdBetween(String value1, String value2) {
            addCriterion("from_cloud_id between", value1, value2, "fromCloudId");
            return (Criteria) this;
        }

        public Criteria andFromCloudIdNotBetween(String value1, String value2) {
            addCriterion("from_cloud_id not between", value1, value2, "fromCloudId");
            return (Criteria) this;
        }

        public Criteria andReferIdIsNull() {
            addCriterion("refer_id is null");
            return (Criteria) this;
        }

        public Criteria andReferIdIsNotNull() {
            addCriterion("refer_id is not null");
            return (Criteria) this;
        }

        public Criteria andReferIdEqualTo(String value) {
            addCriterion("refer_id =", value, "referId");
            return (Criteria) this;
        }

        public Criteria andReferIdNotEqualTo(String value) {
            addCriterion("refer_id <>", value, "referId");
            return (Criteria) this;
        }

        public Criteria andReferIdGreaterThan(String value) {
            addCriterion("refer_id >", value, "referId");
            return (Criteria) this;
        }

        public Criteria andReferIdGreaterThanOrEqualTo(String value) {
            addCriterion("refer_id >=", value, "referId");
            return (Criteria) this;
        }

        public Criteria andReferIdLessThan(String value) {
            addCriterion("refer_id <", value, "referId");
            return (Criteria) this;
        }

        public Criteria andReferIdLessThanOrEqualTo(String value) {
            addCriterion("refer_id <=", value, "referId");
            return (Criteria) this;
        }

        public Criteria andReferIdLike(String value) {
            addCriterion("refer_id like", value, "referId");
            return (Criteria) this;
        }

        public Criteria andReferIdNotLike(String value) {
            addCriterion("refer_id not like", value, "referId");
            return (Criteria) this;
        }

        public Criteria andReferIdIn(List<String> values) {
            addCriterion("refer_id in", values, "referId");
            return (Criteria) this;
        }

        public Criteria andReferIdNotIn(List<String> values) {
            addCriterion("refer_id not in", values, "referId");
            return (Criteria) this;
        }

        public Criteria andReferIdBetween(String value1, String value2) {
            addCriterion("refer_id between", value1, value2, "referId");
            return (Criteria) this;
        }

        public Criteria andReferIdNotBetween(String value1, String value2) {
            addCriterion("refer_id not between", value1, value2, "referId");
            return (Criteria) this;
        }

        public Criteria andFromTenantCodeIsNull() {
            addCriterion("from_tenant_code is null");
            return (Criteria) this;
        }

        public Criteria andFromTenantCodeIsNotNull() {
            addCriterion("from_tenant_code is not null");
            return (Criteria) this;
        }

        public Criteria andFromTenantCodeEqualTo(String value) {
            addCriterion("from_tenant_code =", value, "fromTenantCode");
            return (Criteria) this;
        }

        public Criteria andFromTenantCodeNotEqualTo(String value) {
            addCriterion("from_tenant_code <>", value, "fromTenantCode");
            return (Criteria) this;
        }

        public Criteria andFromTenantCodeGreaterThan(String value) {
            addCriterion("from_tenant_code >", value, "fromTenantCode");
            return (Criteria) this;
        }

        public Criteria andFromTenantCodeGreaterThanOrEqualTo(String value) {
            addCriterion("from_tenant_code >=", value, "fromTenantCode");
            return (Criteria) this;
        }

        public Criteria andFromTenantCodeLessThan(String value) {
            addCriterion("from_tenant_code <", value, "fromTenantCode");
            return (Criteria) this;
        }

        public Criteria andFromTenantCodeLessThanOrEqualTo(String value) {
            addCriterion("from_tenant_code <=", value, "fromTenantCode");
            return (Criteria) this;
        }

        public Criteria andFromTenantCodeLike(String value) {
            addCriterion("from_tenant_code like", value, "fromTenantCode");
            return (Criteria) this;
        }

        public Criteria andFromTenantCodeNotLike(String value) {
            addCriterion("from_tenant_code not like", value, "fromTenantCode");
            return (Criteria) this;
        }

        public Criteria andFromTenantCodeIn(List<String> values) {
            addCriterion("from_tenant_code in", values, "fromTenantCode");
            return (Criteria) this;
        }

        public Criteria andFromTenantCodeNotIn(List<String> values) {
            addCriterion("from_tenant_code not in", values, "fromTenantCode");
            return (Criteria) this;
        }

        public Criteria andFromTenantCodeBetween(String value1, String value2) {
            addCriterion("from_tenant_code between", value1, value2, "fromTenantCode");
            return (Criteria) this;
        }

        public Criteria andFromTenantCodeNotBetween(String value1, String value2) {
            addCriterion("from_tenant_code not between", value1, value2, "fromTenantCode");
            return (Criteria) this;
        }

        public Criteria andPlanStartTimeIsNull() {
            addCriterion("plan_start_time is null");
            return (Criteria) this;
        }

        public Criteria andPlanStartTimeIsNotNull() {
            addCriterion("plan_start_time is not null");
            return (Criteria) this;
        }

        public Criteria andPlanStartTimeEqualTo(Date value) {
            addCriterion("plan_start_time =", value, "planStartTime");
            return (Criteria) this;
        }

        public Criteria andPlanStartTimeNotEqualTo(Date value) {
            addCriterion("plan_start_time <>", value, "planStartTime");
            return (Criteria) this;
        }

        public Criteria andPlanStartTimeGreaterThan(Date value) {
            addCriterion("plan_start_time >", value, "planStartTime");
            return (Criteria) this;
        }

        public Criteria andPlanStartTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("plan_start_time >=", value, "planStartTime");
            return (Criteria) this;
        }

        public Criteria andPlanStartTimeLessThan(Date value) {
            addCriterion("plan_start_time <", value, "planStartTime");
            return (Criteria) this;
        }

        public Criteria andPlanStartTimeLessThanOrEqualTo(Date value) {
            addCriterion("plan_start_time <=", value, "planStartTime");
            return (Criteria) this;
        }

        public Criteria andPlanStartTimeIn(List<Date> values) {
            addCriterion("plan_start_time in", values, "planStartTime");
            return (Criteria) this;
        }

        public Criteria andPlanStartTimeNotIn(List<Date> values) {
            addCriterion("plan_start_time not in", values, "planStartTime");
            return (Criteria) this;
        }

        public Criteria andPlanStartTimeBetween(Date value1, Date value2) {
            addCriterion("plan_start_time between", value1, value2, "planStartTime");
            return (Criteria) this;
        }

        public Criteria andPlanStartTimeNotBetween(Date value1, Date value2) {
            addCriterion("plan_start_time not between", value1, value2, "planStartTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeIsNull() {
            addCriterion("start_time is null");
            return (Criteria) this;
        }

        public Criteria andStartTimeIsNotNull() {
            addCriterion("start_time is not null");
            return (Criteria) this;
        }

        public Criteria andStartTimeEqualTo(Date value) {
            addCriterion("start_time =", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotEqualTo(Date value) {
            addCriterion("start_time <>", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeGreaterThan(Date value) {
            addCriterion("start_time >", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("start_time >=", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeLessThan(Date value) {
            addCriterion("start_time <", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeLessThanOrEqualTo(Date value) {
            addCriterion("start_time <=", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeIn(List<Date> values) {
            addCriterion("start_time in", values, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotIn(List<Date> values) {
            addCriterion("start_time not in", values, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeBetween(Date value1, Date value2) {
            addCriterion("start_time between", value1, value2, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotBetween(Date value1, Date value2) {
            addCriterion("start_time not between", value1, value2, "startTime");
            return (Criteria) this;
        }

        public Criteria andContextRefIsNull() {
            addCriterion("context_ref is null");
            return (Criteria) this;
        }

        public Criteria andContextRefIsNotNull() {
            addCriterion("context_ref is not null");
            return (Criteria) this;
        }

        public Criteria andContextRefEqualTo(String value) {
            addCriterion("context_ref =", value, "contextRef");
            return (Criteria) this;
        }

        public Criteria andContextRefNotEqualTo(String value) {
            addCriterion("context_ref <>", value, "contextRef");
            return (Criteria) this;
        }

        public Criteria andContextRefGreaterThan(String value) {
            addCriterion("context_ref >", value, "contextRef");
            return (Criteria) this;
        }

        public Criteria andContextRefGreaterThanOrEqualTo(String value) {
            addCriterion("context_ref >=", value, "contextRef");
            return (Criteria) this;
        }

        public Criteria andContextRefLessThan(String value) {
            addCriterion("context_ref <", value, "contextRef");
            return (Criteria) this;
        }

        public Criteria andContextRefLessThanOrEqualTo(String value) {
            addCriterion("context_ref <=", value, "contextRef");
            return (Criteria) this;
        }

        public Criteria andContextRefLike(String value) {
            addCriterion("context_ref like", value, "contextRef");
            return (Criteria) this;
        }

        public Criteria andContextRefNotLike(String value) {
            addCriterion("context_ref not like", value, "contextRef");
            return (Criteria) this;
        }

        public Criteria andContextRefIn(List<String> values) {
            addCriterion("context_ref in", values, "contextRef");
            return (Criteria) this;
        }

        public Criteria andContextRefNotIn(List<String> values) {
            addCriterion("context_ref not in", values, "contextRef");
            return (Criteria) this;
        }

        public Criteria andContextRefBetween(String value1, String value2) {
            addCriterion("context_ref between", value1, value2, "contextRef");
            return (Criteria) this;
        }

        public Criteria andContextRefNotBetween(String value1, String value2) {
            addCriterion("context_ref not between", value1, value2, "contextRef");
            return (Criteria) this;
        }

        public Criteria andFinishTimeIsNull() {
            addCriterion("finish_time is null");
            return (Criteria) this;
        }

        public Criteria andFinishTimeIsNotNull() {
            addCriterion("finish_time is not null");
            return (Criteria) this;
        }

        public Criteria andFinishTimeEqualTo(Date value) {
            addCriterion("finish_time =", value, "finishTime");
            return (Criteria) this;
        }

        public Criteria andFinishTimeNotEqualTo(Date value) {
            addCriterion("finish_time <>", value, "finishTime");
            return (Criteria) this;
        }

        public Criteria andFinishTimeGreaterThan(Date value) {
            addCriterion("finish_time >", value, "finishTime");
            return (Criteria) this;
        }

        public Criteria andFinishTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("finish_time >=", value, "finishTime");
            return (Criteria) this;
        }

        public Criteria andFinishTimeLessThan(Date value) {
            addCriterion("finish_time <", value, "finishTime");
            return (Criteria) this;
        }

        public Criteria andFinishTimeLessThanOrEqualTo(Date value) {
            addCriterion("finish_time <=", value, "finishTime");
            return (Criteria) this;
        }

        public Criteria andFinishTimeIn(List<Date> values) {
            addCriterion("finish_time in", values, "finishTime");
            return (Criteria) this;
        }

        public Criteria andFinishTimeNotIn(List<Date> values) {
            addCriterion("finish_time not in", values, "finishTime");
            return (Criteria) this;
        }

        public Criteria andFinishTimeBetween(Date value1, Date value2) {
            addCriterion("finish_time between", value1, value2, "finishTime");
            return (Criteria) this;
        }

        public Criteria andFinishTimeNotBetween(Date value1, Date value2) {
            addCriterion("finish_time not between", value1, value2, "finishTime");
            return (Criteria) this;
        }

        public Criteria andDispatchGroupIsNull() {
            addCriterion("dispatch_group is null");
            return (Criteria) this;
        }

        public Criteria andDispatchGroupIsNotNull() {
            addCriterion("dispatch_group is not null");
            return (Criteria) this;
        }

        public Criteria andDispatchGroupEqualTo(String value) {
            addCriterion("dispatch_group =", value, "dispatchGroup");
            return (Criteria) this;
        }

        public Criteria andDispatchGroupNotEqualTo(String value) {
            addCriterion("dispatch_group <>", value, "dispatchGroup");
            return (Criteria) this;
        }

        public Criteria andDispatchGroupGreaterThan(String value) {
            addCriterion("dispatch_group >", value, "dispatchGroup");
            return (Criteria) this;
        }

        public Criteria andDispatchGroupGreaterThanOrEqualTo(String value) {
            addCriterion("dispatch_group >=", value, "dispatchGroup");
            return (Criteria) this;
        }

        public Criteria andDispatchGroupLessThan(String value) {
            addCriterion("dispatch_group <", value, "dispatchGroup");
            return (Criteria) this;
        }

        public Criteria andDispatchGroupLessThanOrEqualTo(String value) {
            addCriterion("dispatch_group <=", value, "dispatchGroup");
            return (Criteria) this;
        }

        public Criteria andDispatchGroupLike(String value) {
            addCriterion("dispatch_group like", value, "dispatchGroup");
            return (Criteria) this;
        }

        public Criteria andDispatchGroupNotLike(String value) {
            addCriterion("dispatch_group not like", value, "dispatchGroup");
            return (Criteria) this;
        }

        public Criteria andDispatchGroupIn(List<String> values) {
            addCriterion("dispatch_group in", values, "dispatchGroup");
            return (Criteria) this;
        }

        public Criteria andDispatchGroupNotIn(List<String> values) {
            addCriterion("dispatch_group not in", values, "dispatchGroup");
            return (Criteria) this;
        }

        public Criteria andDispatchGroupBetween(String value1, String value2) {
            addCriterion("dispatch_group between", value1, value2, "dispatchGroup");
            return (Criteria) this;
        }

        public Criteria andDispatchGroupNotBetween(String value1, String value2) {
            addCriterion("dispatch_group not between", value1, value2, "dispatchGroup");
            return (Criteria) this;
        }

        public Criteria andParamRefIsNull() {
            addCriterion("param_ref is null");
            return (Criteria) this;
        }

        public Criteria andParamRefIsNotNull() {
            addCriterion("param_ref is not null");
            return (Criteria) this;
        }

        public Criteria andParamRefEqualTo(String value) {
            addCriterion("param_ref =", value, "paramRef");
            return (Criteria) this;
        }

        public Criteria andParamRefNotEqualTo(String value) {
            addCriterion("param_ref <>", value, "paramRef");
            return (Criteria) this;
        }

        public Criteria andParamRefGreaterThan(String value) {
            addCriterion("param_ref >", value, "paramRef");
            return (Criteria) this;
        }

        public Criteria andParamRefGreaterThanOrEqualTo(String value) {
            addCriterion("param_ref >=", value, "paramRef");
            return (Criteria) this;
        }

        public Criteria andParamRefLessThan(String value) {
            addCriterion("param_ref <", value, "paramRef");
            return (Criteria) this;
        }

        public Criteria andParamRefLessThanOrEqualTo(String value) {
            addCriterion("param_ref <=", value, "paramRef");
            return (Criteria) this;
        }

        public Criteria andParamRefLike(String value) {
            addCriterion("param_ref like", value, "paramRef");
            return (Criteria) this;
        }

        public Criteria andParamRefNotLike(String value) {
            addCriterion("param_ref not like", value, "paramRef");
            return (Criteria) this;
        }

        public Criteria andParamRefIn(List<String> values) {
            addCriterion("param_ref in", values, "paramRef");
            return (Criteria) this;
        }

        public Criteria andParamRefNotIn(List<String> values) {
            addCriterion("param_ref not in", values, "paramRef");
            return (Criteria) this;
        }

        public Criteria andParamRefBetween(String value1, String value2) {
            addCriterion("param_ref between", value1, value2, "paramRef");
            return (Criteria) this;
        }

        public Criteria andParamRefNotBetween(String value1, String value2) {
            addCriterion("param_ref not between", value1, value2, "paramRef");
            return (Criteria) this;
        }

        public Criteria andChangeAppsRefIsNull() {
            addCriterion("change_apps_ref is null");
            return (Criteria) this;
        }

        public Criteria andChangeAppsRefIsNotNull() {
            addCriterion("change_apps_ref is not null");
            return (Criteria) this;
        }

        public Criteria andChangeAppsRefEqualTo(String value) {
            addCriterion("change_apps_ref =", value, "changeAppsRef");
            return (Criteria) this;
        }

        public Criteria andChangeAppsRefNotEqualTo(String value) {
            addCriterion("change_apps_ref <>", value, "changeAppsRef");
            return (Criteria) this;
        }

        public Criteria andChangeAppsRefGreaterThan(String value) {
            addCriterion("change_apps_ref >", value, "changeAppsRef");
            return (Criteria) this;
        }

        public Criteria andChangeAppsRefGreaterThanOrEqualTo(String value) {
            addCriterion("change_apps_ref >=", value, "changeAppsRef");
            return (Criteria) this;
        }

        public Criteria andChangeAppsRefLessThan(String value) {
            addCriterion("change_apps_ref <", value, "changeAppsRef");
            return (Criteria) this;
        }

        public Criteria andChangeAppsRefLessThanOrEqualTo(String value) {
            addCriterion("change_apps_ref <=", value, "changeAppsRef");
            return (Criteria) this;
        }

        public Criteria andChangeAppsRefLike(String value) {
            addCriterion("change_apps_ref like", value, "changeAppsRef");
            return (Criteria) this;
        }

        public Criteria andChangeAppsRefNotLike(String value) {
            addCriterion("change_apps_ref not like", value, "changeAppsRef");
            return (Criteria) this;
        }

        public Criteria andChangeAppsRefIn(List<String> values) {
            addCriterion("change_apps_ref in", values, "changeAppsRef");
            return (Criteria) this;
        }

        public Criteria andChangeAppsRefNotIn(List<String> values) {
            addCriterion("change_apps_ref not in", values, "changeAppsRef");
            return (Criteria) this;
        }

        public Criteria andChangeAppsRefBetween(String value1, String value2) {
            addCriterion("change_apps_ref between", value1, value2, "changeAppsRef");
            return (Criteria) this;
        }

        public Criteria andChangeAppsRefNotBetween(String value1, String value2) {
            addCriterion("change_apps_ref not between", value1, value2, "changeAppsRef");
            return (Criteria) this;
        }

        public Criteria andChangeContentRefIsNull() {
            addCriterion("change_content_ref is null");
            return (Criteria) this;
        }

        public Criteria andChangeContentRefIsNotNull() {
            addCriterion("change_content_ref is not null");
            return (Criteria) this;
        }

        public Criteria andChangeContentRefEqualTo(String value) {
            addCriterion("change_content_ref =", value, "changeContentRef");
            return (Criteria) this;
        }

        public Criteria andChangeContentRefNotEqualTo(String value) {
            addCriterion("change_content_ref <>", value, "changeContentRef");
            return (Criteria) this;
        }

        public Criteria andChangeContentRefGreaterThan(String value) {
            addCriterion("change_content_ref >", value, "changeContentRef");
            return (Criteria) this;
        }

        public Criteria andChangeContentRefGreaterThanOrEqualTo(String value) {
            addCriterion("change_content_ref >=", value, "changeContentRef");
            return (Criteria) this;
        }

        public Criteria andChangeContentRefLessThan(String value) {
            addCriterion("change_content_ref <", value, "changeContentRef");
            return (Criteria) this;
        }

        public Criteria andChangeContentRefLessThanOrEqualTo(String value) {
            addCriterion("change_content_ref <=", value, "changeContentRef");
            return (Criteria) this;
        }

        public Criteria andChangeContentRefLike(String value) {
            addCriterion("change_content_ref like", value, "changeContentRef");
            return (Criteria) this;
        }

        public Criteria andChangeContentRefNotLike(String value) {
            addCriterion("change_content_ref not like", value, "changeContentRef");
            return (Criteria) this;
        }

        public Criteria andChangeContentRefIn(List<String> values) {
            addCriterion("change_content_ref in", values, "changeContentRef");
            return (Criteria) this;
        }

        public Criteria andChangeContentRefNotIn(List<String> values) {
            addCriterion("change_content_ref not in", values, "changeContentRef");
            return (Criteria) this;
        }

        public Criteria andChangeContentRefBetween(String value1, String value2) {
            addCriterion("change_content_ref between", value1, value2, "changeContentRef");
            return (Criteria) this;
        }

        public Criteria andChangeContentRefNotBetween(String value1, String value2) {
            addCriterion("change_content_ref not between", value1, value2, "changeContentRef");
            return (Criteria) this;
        }

        public Criteria andParentOrderInfoRefIsNull() {
            addCriterion("parent_order_info_ref is null");
            return (Criteria) this;
        }

        public Criteria andParentOrderInfoRefIsNotNull() {
            addCriterion("parent_order_info_ref is not null");
            return (Criteria) this;
        }

        public Criteria andParentOrderInfoRefEqualTo(String value) {
            addCriterion("parent_order_info_ref =", value, "parentOrderInfoRef");
            return (Criteria) this;
        }

        public Criteria andParentOrderInfoRefNotEqualTo(String value) {
            addCriterion("parent_order_info_ref <>", value, "parentOrderInfoRef");
            return (Criteria) this;
        }

        public Criteria andParentOrderInfoRefGreaterThan(String value) {
            addCriterion("parent_order_info_ref >", value, "parentOrderInfoRef");
            return (Criteria) this;
        }

        public Criteria andParentOrderInfoRefGreaterThanOrEqualTo(String value) {
            addCriterion("parent_order_info_ref >=", value, "parentOrderInfoRef");
            return (Criteria) this;
        }

        public Criteria andParentOrderInfoRefLessThan(String value) {
            addCriterion("parent_order_info_ref <", value, "parentOrderInfoRef");
            return (Criteria) this;
        }

        public Criteria andParentOrderInfoRefLessThanOrEqualTo(String value) {
            addCriterion("parent_order_info_ref <=", value, "parentOrderInfoRef");
            return (Criteria) this;
        }

        public Criteria andParentOrderInfoRefLike(String value) {
            addCriterion("parent_order_info_ref like", value, "parentOrderInfoRef");
            return (Criteria) this;
        }

        public Criteria andParentOrderInfoRefNotLike(String value) {
            addCriterion("parent_order_info_ref not like", value, "parentOrderInfoRef");
            return (Criteria) this;
        }

        public Criteria andParentOrderInfoRefIn(List<String> values) {
            addCriterion("parent_order_info_ref in", values, "parentOrderInfoRef");
            return (Criteria) this;
        }

        public Criteria andParentOrderInfoRefNotIn(List<String> values) {
            addCriterion("parent_order_info_ref not in", values, "parentOrderInfoRef");
            return (Criteria) this;
        }

        public Criteria andParentOrderInfoRefBetween(String value1, String value2) {
            addCriterion("parent_order_info_ref between", value1, value2, "parentOrderInfoRef");
            return (Criteria) this;
        }

        public Criteria andParentOrderInfoRefNotBetween(String value1, String value2) {
            addCriterion("parent_order_info_ref not between", value1, value2, "parentOrderInfoRef");
            return (Criteria) this;
        }

        public Criteria andChangeTargetRefIsNull() {
            addCriterion("change_target_ref is null");
            return (Criteria) this;
        }

        public Criteria andChangeTargetRefIsNotNull() {
            addCriterion("change_target_ref is not null");
            return (Criteria) this;
        }

        public Criteria andChangeTargetRefEqualTo(String value) {
            addCriterion("change_target_ref =", value, "changeTargetRef");
            return (Criteria) this;
        }

        public Criteria andChangeTargetRefNotEqualTo(String value) {
            addCriterion("change_target_ref <>", value, "changeTargetRef");
            return (Criteria) this;
        }

        public Criteria andChangeTargetRefGreaterThan(String value) {
            addCriterion("change_target_ref >", value, "changeTargetRef");
            return (Criteria) this;
        }

        public Criteria andChangeTargetRefGreaterThanOrEqualTo(String value) {
            addCriterion("change_target_ref >=", value, "changeTargetRef");
            return (Criteria) this;
        }

        public Criteria andChangeTargetRefLessThan(String value) {
            addCriterion("change_target_ref <", value, "changeTargetRef");
            return (Criteria) this;
        }

        public Criteria andChangeTargetRefLessThanOrEqualTo(String value) {
            addCriterion("change_target_ref <=", value, "changeTargetRef");
            return (Criteria) this;
        }

        public Criteria andChangeTargetRefLike(String value) {
            addCriterion("change_target_ref like", value, "changeTargetRef");
            return (Criteria) this;
        }

        public Criteria andChangeTargetRefNotLike(String value) {
            addCriterion("change_target_ref not like", value, "changeTargetRef");
            return (Criteria) this;
        }

        public Criteria andChangeTargetRefIn(List<String> values) {
            addCriterion("change_target_ref in", values, "changeTargetRef");
            return (Criteria) this;
        }

        public Criteria andChangeTargetRefNotIn(List<String> values) {
            addCriterion("change_target_ref not in", values, "changeTargetRef");
            return (Criteria) this;
        }

        public Criteria andChangeTargetRefBetween(String value1, String value2) {
            addCriterion("change_target_ref between", value1, value2, "changeTargetRef");
            return (Criteria) this;
        }

        public Criteria andChangeTargetRefNotBetween(String value1, String value2) {
            addCriterion("change_target_ref not between", value1, value2, "changeTargetRef");
            return (Criteria) this;
        }

        public Criteria andRstRefIsNull() {
            addCriterion("rst_ref is null");
            return (Criteria) this;
        }

        public Criteria andRstRefIsNotNull() {
            addCriterion("rst_ref is not null");
            return (Criteria) this;
        }

        public Criteria andRstRefEqualTo(String value) {
            addCriterion("rst_ref =", value, "rstRef");
            return (Criteria) this;
        }

        public Criteria andRstRefNotEqualTo(String value) {
            addCriterion("rst_ref <>", value, "rstRef");
            return (Criteria) this;
        }

        public Criteria andRstRefGreaterThan(String value) {
            addCriterion("rst_ref >", value, "rstRef");
            return (Criteria) this;
        }

        public Criteria andRstRefGreaterThanOrEqualTo(String value) {
            addCriterion("rst_ref >=", value, "rstRef");
            return (Criteria) this;
        }

        public Criteria andRstRefLessThan(String value) {
            addCriterion("rst_ref <", value, "rstRef");
            return (Criteria) this;
        }

        public Criteria andRstRefLessThanOrEqualTo(String value) {
            addCriterion("rst_ref <=", value, "rstRef");
            return (Criteria) this;
        }

        public Criteria andRstRefLike(String value) {
            addCriterion("rst_ref like", value, "rstRef");
            return (Criteria) this;
        }

        public Criteria andRstRefNotLike(String value) {
            addCriterion("rst_ref not like", value, "rstRef");
            return (Criteria) this;
        }

        public Criteria andRstRefIn(List<String> values) {
            addCriterion("rst_ref in", values, "rstRef");
            return (Criteria) this;
        }

        public Criteria andRstRefNotIn(List<String> values) {
            addCriterion("rst_ref not in", values, "rstRef");
            return (Criteria) this;
        }

        public Criteria andRstRefBetween(String value1, String value2) {
            addCriterion("rst_ref between", value1, value2, "rstRef");
            return (Criteria) this;
        }

        public Criteria andRstRefNotBetween(String value1, String value2) {
            addCriterion("rst_ref not between", value1, value2, "rstRef");
            return (Criteria) this;
        }
    }

    /**
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends AbstractGeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }

    /**
     *
     * @mbg.generated
     */
    public enum OrderCondition {
        /**
         *主键
         */
        ORDERID("order_id"),
        /**
         *创建时间
         */
        GMTCREATE("gmt_create"),
        /**
         *修改时间
         */
        GMTMODIFIED("gmt_modified"),
        /**
         *业务工单id
         */
        BIZEXECORDERID("biz_exec_order_id"),
        /**
         *场景key
         */
        CHANGESCENEKEY("change_scene_key"),
        /**
         *变更平台名
         */
        PLATFORM("platform"),
        /**
         *traceId
         */
        TRACEID("trace_id"),
        /**
         *分区位;提供给node使用
         */
        UID("uid"),
        /**
         *变更坐标
         */
        COORD("coord"),
        /**
         *变更标题
         */
        CHANGETITLE("change_title"),
        /**
         *变更地址
         */
        CHANGEURL("change_url"),
        /**
         *变更情景码
         */
        CHANGESCENARIOCODE("change_scenario_code"),
        /**
         *变更单状态
         */
        STATUS("status"),
        /**
         *变更执行单创建人
         */
        CREATOR("creator"),
        /**
         *变更执行单执行人
         */
        EXECUTOR("executor"),
        /**
         *变更阶段（环境），多个用逗号隔开
         */
        CHANGEPHASES("change_phases"),
        /**
         *变更消息
         */
        MSG("msg"),
        /**
         *可信租户
         */
        TENANTCODE("tenant_code"),
        /**
         *来源云id
         */
        FROMCLOUDID("from_cloud_id"),
        /**
         *来源工单id
         */
        REFERID("refer_id"),
        /**
         *来源租户
         */
        FROMTENANTCODE("from_tenant_code"),
        /**
         *变更计划开始时间
         */
        PLANSTARTTIME("plan_start_time"),
        /**
         *变更实际执行时间
         */
        STARTTIME("start_time"),
        /**
         *上下文扩展信息
         */
        CONTEXTREF("context_ref"),
        /**
         *变更结束时间
         */
        FINISHTIME("finish_time"),
        /**
         *变更单调度组
         */
        DISPATCHGROUP("dispatch_group"),
        /**
         *变更参数
         */
        PARAMREF("param_ref"),
        /**
         *影响的应用
         */
        CHANGEAPPSREF("change_apps_ref"),
        /**
         *变更内容对象
         */
        CHANGECONTENTREF("change_content_ref"),
        /**
         *变更父工单信息。json格式
         */
        PARENTORDERINFOREF("parent_order_info_ref"),
        /**
         *变更目标对象
         */
        CHANGETARGETREF("change_target_ref"),
        /**
         *变更结果json
         */
        RSTREF("rst_ref");

        private String columnName;

        OrderCondition(String columnName) {
            this.columnName = columnName;
        }

        public String getColumnName() {
            return columnName;
        }

        public static OrderCondition getEnumByName(String name) {
            OrderCondition[] orderConditions = OrderCondition.values();
            for (OrderCondition orderCondition : orderConditions) {
                if (orderCondition.name().equalsIgnoreCase(name)) {
                    return orderCondition;
                }
            }
            throw new RuntimeException("OrderCondition of " + name + " enum not exist");
        }

        @Override
        public String toString() {
            return columnName;
        }
    }

    /**
     *
     * @mbg.generated
     */
    public enum SortType {
        /**
         * 升序
         */
        ASC("asc"),
        /**
         * 降序
         */
        DESC("desc");

        private String value;

        SortType(String value) {
            this.value = value;
        }

        public String getValue() {
            return value;
        }

        public static SortType getEnumByName(String name) {
            SortType[] sortTypes = SortType.values();
            for (SortType sortType : sortTypes) {
                if (sortType.name().equalsIgnoreCase(name)) {
                    return sortType;
                }
            }
            throw new RuntimeException("SortType of " + name + " enum not exist");
        }

        @Override
        public String toString() {
            return value;
        }
    }
}