/*
 * MIT License
 *
 * Copyright (c) [2023]
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package com.alipay.altershield.defender.changewindow.dal.dataobject;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * This class was generated by Ali-Generator
 *
 * @author shengzhang
 */
public class MetaReleaseChangeParam {
    /**
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     *
     * @mbg.generated
     */
    @Deprecated
    protected boolean distinct;

    /**
     *
     * @mbg.generated
     */
    protected boolean page;

    /**
     *
     * @mbg.generated
     */
    protected int pageIndex;

    /**
     *
     * @mbg.generated
     */
    protected int pageSize;

    /**
     *
     * @mbg.generated
     */
    protected int pageStart;

    /**
     *
     * @mbg.generated
     */
    protected String distinctSql;

    /**
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     *
     * @mbg.generated
     */
    public MetaReleaseChangeParam() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * @param orderCondition
     * @param sortType
     * @return
     *
     * @mbg.generated
     */
    public MetaReleaseChangeParam appendOrderByClause(OrderCondition orderCondition,
                                                      SortType sortType) {
        if (null != orderByClause) {
            orderByClause = orderByClause + ", " + orderCondition.getColumnName() + " "
                    + sortType.getValue();
        } else {
            orderByClause = orderCondition.getColumnName() + " " + sortType.getValue();
        }
        return this;
    }

    /**
     * @return
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * @param distinct
     *
     * @mbg.generated
     */
    @Deprecated
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * @return
     *
     * @mbg.generated
     */
    @Deprecated
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * @param page
     * @return
     *
     * @mbg.generated
     */
    public MetaReleaseChangeParam setPage(boolean page) {
        this.page = page;
        return this;
    }

    /**
     * @return
     *
     * @mbg.generated
     */
    public boolean isPage() {
        return page;
    }

    /**
     * @return
     *
     * @mbg.generated
     */
    public int getPageIndex() {
        return pageIndex;
    }

    /**
     * @param pageSize
     * @return
     *
     * @mbg.generated
     */
    public MetaReleaseChangeParam setPageSize(int pageSize) {
        this.pageSize = pageSize < 1 ? 10 : pageSize;
        this.pageIndex = pageStart < 1 ? 0 : (pageStart - 1) * this.pageSize;
        return this;
    }

    /**
     * @return
     *
     * @mbg.generated
     */
    public int getPageSize() {
        return pageSize;
    }

    /**
     * @param pageStart
     * @return
     *
     * @mbg.generated
     */
    public MetaReleaseChangeParam setPageStart(int pageStart) {
        this.pageStart = pageStart < 1 ? 1 : pageStart;
        this.pageIndex = (this.pageStart - 1) * this.pageSize;
        return this;
    }

    /**
     * @return
     *
     * @mbg.generated
     */
    public int getPageStart() {
        return pageStart;
    }

    /**
     * @param pageStart
     * @param pageSize
     *
     * @mbg.generated
     */
    public void setPagination(int pageStart, int pageSize) {
        this.page = true;
        this.pageSize = pageSize < 1 ? 10 : pageSize;
        this.pageIndex = pageStart < 1 ? 0 : (pageStart - 1) * this.pageSize;
    }

    /**
     * @param condition
     * @return
     *
     * @mbg.generated
     */
    public MetaReleaseChangeParam appendDistinct(OrderCondition condition) {
        if (null != distinctSql) {
            distinctSql = distinctSql + ", " + condition.getColumnName();
        } else {
            distinctSql = condition.getColumnName();
        }
        return this;
    }

    /**
     * @return
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * @param criteria
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * @return
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * @return
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * @return
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     *
     * @mbg.generated
     */
    protected abstract static class AbstractGeneratedCriteria {
        protected List<Criterion> criteria;

        protected AbstractGeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2,
                String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIsNull() {
            addCriterion("gmt_create is null");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIsNotNull() {
            addCriterion("gmt_create is not null");
            return (Criteria) this;
        }

        public Criteria andGmtCreateEqualTo(Date value) {
            addCriterion("gmt_create =", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotEqualTo(Date value) {
            addCriterion("gmt_create <>", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateGreaterThan(Date value) {
            addCriterion("gmt_create >", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateGreaterThanOrEqualTo(Date value) {
            addCriterion("gmt_create >=", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateLessThan(Date value) {
            addCriterion("gmt_create <", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateLessThanOrEqualTo(Date value) {
            addCriterion("gmt_create <=", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIn(List<Date> values) {
            addCriterion("gmt_create in", values, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotIn(List<Date> values) {
            addCriterion("gmt_create not in", values, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateBetween(Date value1, Date value2) {
            addCriterion("gmt_create between", value1, value2, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotBetween(Date value1, Date value2) {
            addCriterion("gmt_create not between", value1, value2, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIsNull() {
            addCriterion("gmt_modified is null");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIsNotNull() {
            addCriterion("gmt_modified is not null");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedEqualTo(Date value) {
            addCriterion("gmt_modified =", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotEqualTo(Date value) {
            addCriterion("gmt_modified <>", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedGreaterThan(Date value) {
            addCriterion("gmt_modified >", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedGreaterThanOrEqualTo(Date value) {
            addCriterion("gmt_modified >=", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedLessThan(Date value) {
            addCriterion("gmt_modified <", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedLessThanOrEqualTo(Date value) {
            addCriterion("gmt_modified <=", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIn(List<Date> values) {
            addCriterion("gmt_modified in", values, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotIn(List<Date> values) {
            addCriterion("gmt_modified not in", values, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedBetween(Date value1, Date value2) {
            addCriterion("gmt_modified between", value1, value2, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotBetween(Date value1, Date value2) {
            addCriterion("gmt_modified not between", value1, value2, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andOperatorIsNull() {
            addCriterion("operator is null");
            return (Criteria) this;
        }

        public Criteria andOperatorIsNotNull() {
            addCriterion("operator is not null");
            return (Criteria) this;
        }

        public Criteria andOperatorEqualTo(String value) {
            addCriterion("operator =", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorNotEqualTo(String value) {
            addCriterion("operator <>", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorGreaterThan(String value) {
            addCriterion("operator >", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorGreaterThanOrEqualTo(String value) {
            addCriterion("operator >=", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorLessThan(String value) {
            addCriterion("operator <", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorLessThanOrEqualTo(String value) {
            addCriterion("operator <=", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorLike(String value) {
            addCriterion("operator like", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorNotLike(String value) {
            addCriterion("operator not like", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorIn(List<String> values) {
            addCriterion("operator in", values, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorNotIn(List<String> values) {
            addCriterion("operator not in", values, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorBetween(String value1, String value2) {
            addCriterion("operator between", value1, value2, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorNotBetween(String value1, String value2) {
            addCriterion("operator not between", value1, value2, "operator");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andBlockchangeIdIsNull() {
            addCriterion("blockchange_id is null");
            return (Criteria) this;
        }

        public Criteria andBlockchangeIdIsNotNull() {
            addCriterion("blockchange_id is not null");
            return (Criteria) this;
        }

        public Criteria andBlockchangeIdEqualTo(String value) {
            addCriterion("blockchange_id =", value, "blockchangeId");
            return (Criteria) this;
        }

        public Criteria andBlockchangeIdNotEqualTo(String value) {
            addCriterion("blockchange_id <>", value, "blockchangeId");
            return (Criteria) this;
        }

        public Criteria andBlockchangeIdGreaterThan(String value) {
            addCriterion("blockchange_id >", value, "blockchangeId");
            return (Criteria) this;
        }

        public Criteria andBlockchangeIdGreaterThanOrEqualTo(String value) {
            addCriterion("blockchange_id >=", value, "blockchangeId");
            return (Criteria) this;
        }

        public Criteria andBlockchangeIdLessThan(String value) {
            addCriterion("blockchange_id <", value, "blockchangeId");
            return (Criteria) this;
        }

        public Criteria andBlockchangeIdLessThanOrEqualTo(String value) {
            addCriterion("blockchange_id <=", value, "blockchangeId");
            return (Criteria) this;
        }

        public Criteria andBlockchangeIdLike(String value) {
            addCriterion("blockchange_id like", value, "blockchangeId");
            return (Criteria) this;
        }

        public Criteria andBlockchangeIdNotLike(String value) {
            addCriterion("blockchange_id not like", value, "blockchangeId");
            return (Criteria) this;
        }

        public Criteria andBlockchangeIdIn(List<String> values) {
            addCriterion("blockchange_id in", values, "blockchangeId");
            return (Criteria) this;
        }

        public Criteria andBlockchangeIdNotIn(List<String> values) {
            addCriterion("blockchange_id not in", values, "blockchangeId");
            return (Criteria) this;
        }

        public Criteria andBlockchangeIdBetween(String value1, String value2) {
            addCriterion("blockchange_id between", value1, value2, "blockchangeId");
            return (Criteria) this;
        }

        public Criteria andBlockchangeIdNotBetween(String value1, String value2) {
            addCriterion("blockchange_id not between", value1, value2, "blockchangeId");
            return (Criteria) this;
        }

        public Criteria andBlockchangeNameIsNull() {
            addCriterion("blockchange_name is null");
            return (Criteria) this;
        }

        public Criteria andBlockchangeNameIsNotNull() {
            addCriterion("blockchange_name is not null");
            return (Criteria) this;
        }

        public Criteria andBlockchangeNameEqualTo(String value) {
            addCriterion("blockchange_name =", value, "blockchangeName");
            return (Criteria) this;
        }

        public Criteria andBlockchangeNameNotEqualTo(String value) {
            addCriterion("blockchange_name <>", value, "blockchangeName");
            return (Criteria) this;
        }

        public Criteria andBlockchangeNameGreaterThan(String value) {
            addCriterion("blockchange_name >", value, "blockchangeName");
            return (Criteria) this;
        }

        public Criteria andBlockchangeNameGreaterThanOrEqualTo(String value) {
            addCriterion("blockchange_name >=", value, "blockchangeName");
            return (Criteria) this;
        }

        public Criteria andBlockchangeNameLessThan(String value) {
            addCriterion("blockchange_name <", value, "blockchangeName");
            return (Criteria) this;
        }

        public Criteria andBlockchangeNameLessThanOrEqualTo(String value) {
            addCriterion("blockchange_name <=", value, "blockchangeName");
            return (Criteria) this;
        }

        public Criteria andBlockchangeNameLike(String value) {
            addCriterion("blockchange_name like", value, "blockchangeName");
            return (Criteria) this;
        }

        public Criteria andBlockchangeNameNotLike(String value) {
            addCriterion("blockchange_name not like", value, "blockchangeName");
            return (Criteria) this;
        }

        public Criteria andBlockchangeNameIn(List<String> values) {
            addCriterion("blockchange_name in", values, "blockchangeName");
            return (Criteria) this;
        }

        public Criteria andBlockchangeNameNotIn(List<String> values) {
            addCriterion("blockchange_name not in", values, "blockchangeName");
            return (Criteria) this;
        }

        public Criteria andBlockchangeNameBetween(String value1, String value2) {
            addCriterion("blockchange_name between", value1, value2, "blockchangeName");
            return (Criteria) this;
        }

        public Criteria andBlockchangeNameNotBetween(String value1, String value2) {
            addCriterion("blockchange_name not between", value1, value2, "blockchangeName");
            return (Criteria) this;
        }

        public Criteria andStartTimeIsNull() {
            addCriterion("start_time is null");
            return (Criteria) this;
        }

        public Criteria andStartTimeIsNotNull() {
            addCriterion("start_time is not null");
            return (Criteria) this;
        }

        public Criteria andStartTimeEqualTo(Date value) {
            addCriterion("start_time =", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotEqualTo(Date value) {
            addCriterion("start_time <>", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeGreaterThan(Date value) {
            addCriterion("start_time >", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("start_time >=", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeLessThan(Date value) {
            addCriterion("start_time <", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeLessThanOrEqualTo(Date value) {
            addCriterion("start_time <=", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeIn(List<Date> values) {
            addCriterion("start_time in", values, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotIn(List<Date> values) {
            addCriterion("start_time not in", values, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeBetween(Date value1, Date value2) {
            addCriterion("start_time between", value1, value2, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotBetween(Date value1, Date value2) {
            addCriterion("start_time not between", value1, value2, "startTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeIsNull() {
            addCriterion("end_time is null");
            return (Criteria) this;
        }

        public Criteria andEndTimeIsNotNull() {
            addCriterion("end_time is not null");
            return (Criteria) this;
        }

        public Criteria andEndTimeEqualTo(Date value) {
            addCriterion("end_time =", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotEqualTo(Date value) {
            addCriterion("end_time <>", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeGreaterThan(Date value) {
            addCriterion("end_time >", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("end_time >=", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeLessThan(Date value) {
            addCriterion("end_time <", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeLessThanOrEqualTo(Date value) {
            addCriterion("end_time <=", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeIn(List<Date> values) {
            addCriterion("end_time in", values, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotIn(List<Date> values) {
            addCriterion("end_time not in", values, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeBetween(Date value1, Date value2) {
            addCriterion("end_time between", value1, value2, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotBetween(Date value1, Date value2) {
            addCriterion("end_time not between", value1, value2, "endTime");
            return (Criteria) this;
        }

        public Criteria andEffectEnvironmentIsNull() {
            addCriterion("effect_environment is null");
            return (Criteria) this;
        }

        public Criteria andEffectEnvironmentIsNotNull() {
            addCriterion("effect_environment is not null");
            return (Criteria) this;
        }

        public Criteria andEffectEnvironmentEqualTo(String value) {
            addCriterion("effect_environment =", value, "effectEnvironment");
            return (Criteria) this;
        }

        public Criteria andEffectEnvironmentNotEqualTo(String value) {
            addCriterion("effect_environment <>", value, "effectEnvironment");
            return (Criteria) this;
        }

        public Criteria andEffectEnvironmentGreaterThan(String value) {
            addCriterion("effect_environment >", value, "effectEnvironment");
            return (Criteria) this;
        }

        public Criteria andEffectEnvironmentGreaterThanOrEqualTo(String value) {
            addCriterion("effect_environment >=", value, "effectEnvironment");
            return (Criteria) this;
        }

        public Criteria andEffectEnvironmentLessThan(String value) {
            addCriterion("effect_environment <", value, "effectEnvironment");
            return (Criteria) this;
        }

        public Criteria andEffectEnvironmentLessThanOrEqualTo(String value) {
            addCriterion("effect_environment <=", value, "effectEnvironment");
            return (Criteria) this;
        }

        public Criteria andEffectEnvironmentLike(String value) {
            addCriterion("effect_environment like", value, "effectEnvironment");
            return (Criteria) this;
        }

        public Criteria andEffectEnvironmentNotLike(String value) {
            addCriterion("effect_environment not like", value, "effectEnvironment");
            return (Criteria) this;
        }

        public Criteria andEffectEnvironmentIn(List<String> values) {
            addCriterion("effect_environment in", values, "effectEnvironment");
            return (Criteria) this;
        }

        public Criteria andEffectEnvironmentNotIn(List<String> values) {
            addCriterion("effect_environment not in", values, "effectEnvironment");
            return (Criteria) this;
        }

        public Criteria andEffectEnvironmentBetween(String value1, String value2) {
            addCriterion("effect_environment between", value1, value2, "effectEnvironment");
            return (Criteria) this;
        }

        public Criteria andEffectEnvironmentNotBetween(String value1, String value2) {
            addCriterion("effect_environment not between", value1, value2, "effectEnvironment");
            return (Criteria) this;
        }

        public Criteria andReasonRefIsNull() {
            addCriterion("reason_ref is null");
            return (Criteria) this;
        }

        public Criteria andReasonRefIsNotNull() {
            addCriterion("reason_ref is not null");
            return (Criteria) this;
        }

        public Criteria andReasonRefEqualTo(String value) {
            addCriterion("reason_ref =", value, "reasonRef");
            return (Criteria) this;
        }

        public Criteria andReasonRefNotEqualTo(String value) {
            addCriterion("reason_ref <>", value, "reasonRef");
            return (Criteria) this;
        }

        public Criteria andReasonRefGreaterThan(String value) {
            addCriterion("reason_ref >", value, "reasonRef");
            return (Criteria) this;
        }

        public Criteria andReasonRefGreaterThanOrEqualTo(String value) {
            addCriterion("reason_ref >=", value, "reasonRef");
            return (Criteria) this;
        }

        public Criteria andReasonRefLessThan(String value) {
            addCriterion("reason_ref <", value, "reasonRef");
            return (Criteria) this;
        }

        public Criteria andReasonRefLessThanOrEqualTo(String value) {
            addCriterion("reason_ref <=", value, "reasonRef");
            return (Criteria) this;
        }

        public Criteria andReasonRefLike(String value) {
            addCriterion("reason_ref like", value, "reasonRef");
            return (Criteria) this;
        }

        public Criteria andReasonRefNotLike(String value) {
            addCriterion("reason_ref not like", value, "reasonRef");
            return (Criteria) this;
        }

        public Criteria andReasonRefIn(List<String> values) {
            addCriterion("reason_ref in", values, "reasonRef");
            return (Criteria) this;
        }

        public Criteria andReasonRefNotIn(List<String> values) {
            addCriterion("reason_ref not in", values, "reasonRef");
            return (Criteria) this;
        }

        public Criteria andReasonRefBetween(String value1, String value2) {
            addCriterion("reason_ref between", value1, value2, "reasonRef");
            return (Criteria) this;
        }

        public Criteria andReasonRefNotBetween(String value1, String value2) {
            addCriterion("reason_ref not between", value1, value2, "reasonRef");
            return (Criteria) this;
        }

        public Criteria andArchdomainRangeIsNull() {
            addCriterion("archdomain_range is null");
            return (Criteria) this;
        }

        public Criteria andArchdomainRangeIsNotNull() {
            addCriterion("archdomain_range is not null");
            return (Criteria) this;
        }

        public Criteria andArchdomainRangeEqualTo(String value) {
            addCriterion("archdomain_range =", value, "archdomainRange");
            return (Criteria) this;
        }

        public Criteria andArchdomainRangeNotEqualTo(String value) {
            addCriterion("archdomain_range <>", value, "archdomainRange");
            return (Criteria) this;
        }

        public Criteria andArchdomainRangeGreaterThan(String value) {
            addCriterion("archdomain_range >", value, "archdomainRange");
            return (Criteria) this;
        }

        public Criteria andArchdomainRangeGreaterThanOrEqualTo(String value) {
            addCriterion("archdomain_range >=", value, "archdomainRange");
            return (Criteria) this;
        }

        public Criteria andArchdomainRangeLessThan(String value) {
            addCriterion("archdomain_range <", value, "archdomainRange");
            return (Criteria) this;
        }

        public Criteria andArchdomainRangeLessThanOrEqualTo(String value) {
            addCriterion("archdomain_range <=", value, "archdomainRange");
            return (Criteria) this;
        }

        public Criteria andArchdomainRangeLike(String value) {
            addCriterion("archdomain_range like", value, "archdomainRange");
            return (Criteria) this;
        }

        public Criteria andArchdomainRangeNotLike(String value) {
            addCriterion("archdomain_range not like", value, "archdomainRange");
            return (Criteria) this;
        }

        public Criteria andArchdomainRangeIn(List<String> values) {
            addCriterion("archdomain_range in", values, "archdomainRange");
            return (Criteria) this;
        }

        public Criteria andArchdomainRangeNotIn(List<String> values) {
            addCriterion("archdomain_range not in", values, "archdomainRange");
            return (Criteria) this;
        }

        public Criteria andArchdomainRangeBetween(String value1, String value2) {
            addCriterion("archdomain_range between", value1, value2, "archdomainRange");
            return (Criteria) this;
        }

        public Criteria andArchdomainRangeNotBetween(String value1, String value2) {
            addCriterion("archdomain_range not between", value1, value2, "archdomainRange");
            return (Criteria) this;
        }

        public Criteria andBusgroupRangeIsNull() {
            addCriterion("busgroup_range is null");
            return (Criteria) this;
        }

        public Criteria andBusgroupRangeIsNotNull() {
            addCriterion("busgroup_range is not null");
            return (Criteria) this;
        }

        public Criteria andBusgroupRangeEqualTo(String value) {
            addCriterion("busgroup_range =", value, "busgroupRange");
            return (Criteria) this;
        }

        public Criteria andBusgroupRangeNotEqualTo(String value) {
            addCriterion("busgroup_range <>", value, "busgroupRange");
            return (Criteria) this;
        }

        public Criteria andBusgroupRangeGreaterThan(String value) {
            addCriterion("busgroup_range >", value, "busgroupRange");
            return (Criteria) this;
        }

        public Criteria andBusgroupRangeGreaterThanOrEqualTo(String value) {
            addCriterion("busgroup_range >=", value, "busgroupRange");
            return (Criteria) this;
        }

        public Criteria andBusgroupRangeLessThan(String value) {
            addCriterion("busgroup_range <", value, "busgroupRange");
            return (Criteria) this;
        }

        public Criteria andBusgroupRangeLessThanOrEqualTo(String value) {
            addCriterion("busgroup_range <=", value, "busgroupRange");
            return (Criteria) this;
        }

        public Criteria andBusgroupRangeLike(String value) {
            addCriterion("busgroup_range like", value, "busgroupRange");
            return (Criteria) this;
        }

        public Criteria andBusgroupRangeNotLike(String value) {
            addCriterion("busgroup_range not like", value, "busgroupRange");
            return (Criteria) this;
        }

        public Criteria andBusgroupRangeIn(List<String> values) {
            addCriterion("busgroup_range in", values, "busgroupRange");
            return (Criteria) this;
        }

        public Criteria andBusgroupRangeNotIn(List<String> values) {
            addCriterion("busgroup_range not in", values, "busgroupRange");
            return (Criteria) this;
        }

        public Criteria andBusgroupRangeBetween(String value1, String value2) {
            addCriterion("busgroup_range between", value1, value2, "busgroupRange");
            return (Criteria) this;
        }

        public Criteria andBusgroupRangeNotBetween(String value1, String value2) {
            addCriterion("busgroup_range not between", value1, value2, "busgroupRange");
            return (Criteria) this;
        }

        public Criteria andChangeTargetTypeIsNull() {
            addCriterion("change_target_type is null");
            return (Criteria) this;
        }

        public Criteria andChangeTargetTypeIsNotNull() {
            addCriterion("change_target_type is not null");
            return (Criteria) this;
        }

        public Criteria andChangeTargetTypeEqualTo(String value) {
            addCriterion("change_target_type =", value, "changeTargetType");
            return (Criteria) this;
        }

        public Criteria andChangeTargetTypeNotEqualTo(String value) {
            addCriterion("change_target_type <>", value, "changeTargetType");
            return (Criteria) this;
        }

        public Criteria andChangeTargetTypeGreaterThan(String value) {
            addCriterion("change_target_type >", value, "changeTargetType");
            return (Criteria) this;
        }

        public Criteria andChangeTargetTypeGreaterThanOrEqualTo(String value) {
            addCriterion("change_target_type >=", value, "changeTargetType");
            return (Criteria) this;
        }

        public Criteria andChangeTargetTypeLessThan(String value) {
            addCriterion("change_target_type <", value, "changeTargetType");
            return (Criteria) this;
        }

        public Criteria andChangeTargetTypeLessThanOrEqualTo(String value) {
            addCriterion("change_target_type <=", value, "changeTargetType");
            return (Criteria) this;
        }

        public Criteria andChangeTargetTypeLike(String value) {
            addCriterion("change_target_type like", value, "changeTargetType");
            return (Criteria) this;
        }

        public Criteria andChangeTargetTypeNotLike(String value) {
            addCriterion("change_target_type not like", value, "changeTargetType");
            return (Criteria) this;
        }

        public Criteria andChangeTargetTypeIn(List<String> values) {
            addCriterion("change_target_type in", values, "changeTargetType");
            return (Criteria) this;
        }

        public Criteria andChangeTargetTypeNotIn(List<String> values) {
            addCriterion("change_target_type not in", values, "changeTargetType");
            return (Criteria) this;
        }

        public Criteria andChangeTargetTypeBetween(String value1, String value2) {
            addCriterion("change_target_type between", value1, value2, "changeTargetType");
            return (Criteria) this;
        }

        public Criteria andChangeTargetTypeNotBetween(String value1, String value2) {
            addCriterion("change_target_type not between", value1, value2, "changeTargetType");
            return (Criteria) this;
        }

        public Criteria andConfigRefIsNull() {
            addCriterion("config_ref is null");
            return (Criteria) this;
        }

        public Criteria andConfigRefIsNotNull() {
            addCriterion("config_ref is not null");
            return (Criteria) this;
        }

        public Criteria andConfigRefEqualTo(String value) {
            addCriterion("config_ref =", value, "configRef");
            return (Criteria) this;
        }

        public Criteria andConfigRefNotEqualTo(String value) {
            addCriterion("config_ref <>", value, "configRef");
            return (Criteria) this;
        }

        public Criteria andConfigRefGreaterThan(String value) {
            addCriterion("config_ref >", value, "configRef");
            return (Criteria) this;
        }

        public Criteria andConfigRefGreaterThanOrEqualTo(String value) {
            addCriterion("config_ref >=", value, "configRef");
            return (Criteria) this;
        }

        public Criteria andConfigRefLessThan(String value) {
            addCriterion("config_ref <", value, "configRef");
            return (Criteria) this;
        }

        public Criteria andConfigRefLessThanOrEqualTo(String value) {
            addCriterion("config_ref <=", value, "configRef");
            return (Criteria) this;
        }

        public Criteria andConfigRefLike(String value) {
            addCriterion("config_ref like", value, "configRef");
            return (Criteria) this;
        }

        public Criteria andConfigRefNotLike(String value) {
            addCriterion("config_ref not like", value, "configRef");
            return (Criteria) this;
        }

        public Criteria andConfigRefIn(List<String> values) {
            addCriterion("config_ref in", values, "configRef");
            return (Criteria) this;
        }

        public Criteria andConfigRefNotIn(List<String> values) {
            addCriterion("config_ref not in", values, "configRef");
            return (Criteria) this;
        }

        public Criteria andConfigRefBetween(String value1, String value2) {
            addCriterion("config_ref between", value1, value2, "configRef");
            return (Criteria) this;
        }

        public Criteria andConfigRefNotBetween(String value1, String value2) {
            addCriterion("config_ref not between", value1, value2, "configRef");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("status like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("status not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andApprovalFlowIdIsNull() {
            addCriterion("approval_flow_id is null");
            return (Criteria) this;
        }

        public Criteria andApprovalFlowIdIsNotNull() {
            addCriterion("approval_flow_id is not null");
            return (Criteria) this;
        }

        public Criteria andApprovalFlowIdEqualTo(String value) {
            addCriterion("approval_flow_id =", value, "approvalFlowId");
            return (Criteria) this;
        }

        public Criteria andApprovalFlowIdNotEqualTo(String value) {
            addCriterion("approval_flow_id <>", value, "approvalFlowId");
            return (Criteria) this;
        }

        public Criteria andApprovalFlowIdGreaterThan(String value) {
            addCriterion("approval_flow_id >", value, "approvalFlowId");
            return (Criteria) this;
        }

        public Criteria andApprovalFlowIdGreaterThanOrEqualTo(String value) {
            addCriterion("approval_flow_id >=", value, "approvalFlowId");
            return (Criteria) this;
        }

        public Criteria andApprovalFlowIdLessThan(String value) {
            addCriterion("approval_flow_id <", value, "approvalFlowId");
            return (Criteria) this;
        }

        public Criteria andApprovalFlowIdLessThanOrEqualTo(String value) {
            addCriterion("approval_flow_id <=", value, "approvalFlowId");
            return (Criteria) this;
        }

        public Criteria andApprovalFlowIdLike(String value) {
            addCriterion("approval_flow_id like", value, "approvalFlowId");
            return (Criteria) this;
        }

        public Criteria andApprovalFlowIdNotLike(String value) {
            addCriterion("approval_flow_id not like", value, "approvalFlowId");
            return (Criteria) this;
        }

        public Criteria andApprovalFlowIdIn(List<String> values) {
            addCriterion("approval_flow_id in", values, "approvalFlowId");
            return (Criteria) this;
        }

        public Criteria andApprovalFlowIdNotIn(List<String> values) {
            addCriterion("approval_flow_id not in", values, "approvalFlowId");
            return (Criteria) this;
        }

        public Criteria andApprovalFlowIdBetween(String value1, String value2) {
            addCriterion("approval_flow_id between", value1, value2, "approvalFlowId");
            return (Criteria) this;
        }

        public Criteria andApprovalFlowIdNotBetween(String value1, String value2) {
            addCriterion("approval_flow_id not between", value1, value2, "approvalFlowId");
            return (Criteria) this;
        }

        public Criteria andReasonTypeIsNull() {
            addCriterion("reason_type is null");
            return (Criteria) this;
        }

        public Criteria andReasonTypeIsNotNull() {
            addCriterion("reason_type is not null");
            return (Criteria) this;
        }

        public Criteria andReasonTypeEqualTo(String value) {
            addCriterion("reason_type =", value, "reasonType");
            return (Criteria) this;
        }

        public Criteria andReasonTypeNotEqualTo(String value) {
            addCriterion("reason_type <>", value, "reasonType");
            return (Criteria) this;
        }

        public Criteria andReasonTypeGreaterThan(String value) {
            addCriterion("reason_type >", value, "reasonType");
            return (Criteria) this;
        }

        public Criteria andReasonTypeGreaterThanOrEqualTo(String value) {
            addCriterion("reason_type >=", value, "reasonType");
            return (Criteria) this;
        }

        public Criteria andReasonTypeLessThan(String value) {
            addCriterion("reason_type <", value, "reasonType");
            return (Criteria) this;
        }

        public Criteria andReasonTypeLessThanOrEqualTo(String value) {
            addCriterion("reason_type <=", value, "reasonType");
            return (Criteria) this;
        }

        public Criteria andReasonTypeLike(String value) {
            addCriterion("reason_type like", value, "reasonType");
            return (Criteria) this;
        }

        public Criteria andReasonTypeNotLike(String value) {
            addCriterion("reason_type not like", value, "reasonType");
            return (Criteria) this;
        }

        public Criteria andReasonTypeIn(List<String> values) {
            addCriterion("reason_type in", values, "reasonType");
            return (Criteria) this;
        }

        public Criteria andReasonTypeNotIn(List<String> values) {
            addCriterion("reason_type not in", values, "reasonType");
            return (Criteria) this;
        }

        public Criteria andReasonTypeBetween(String value1, String value2) {
            addCriterion("reason_type between", value1, value2, "reasonType");
            return (Criteria) this;
        }

        public Criteria andReasonTypeNotBetween(String value1, String value2) {
            addCriterion("reason_type not between", value1, value2, "reasonType");
            return (Criteria) this;
        }

        public Criteria andBizInfluenceIsNull() {
            addCriterion("biz_influence is null");
            return (Criteria) this;
        }

        public Criteria andBizInfluenceIsNotNull() {
            addCriterion("biz_influence is not null");
            return (Criteria) this;
        }

        public Criteria andBizInfluenceEqualTo(String value) {
            addCriterion("biz_influence =", value, "bizInfluence");
            return (Criteria) this;
        }

        public Criteria andBizInfluenceNotEqualTo(String value) {
            addCriterion("biz_influence <>", value, "bizInfluence");
            return (Criteria) this;
        }

        public Criteria andBizInfluenceGreaterThan(String value) {
            addCriterion("biz_influence >", value, "bizInfluence");
            return (Criteria) this;
        }

        public Criteria andBizInfluenceGreaterThanOrEqualTo(String value) {
            addCriterion("biz_influence >=", value, "bizInfluence");
            return (Criteria) this;
        }

        public Criteria andBizInfluenceLessThan(String value) {
            addCriterion("biz_influence <", value, "bizInfluence");
            return (Criteria) this;
        }

        public Criteria andBizInfluenceLessThanOrEqualTo(String value) {
            addCriterion("biz_influence <=", value, "bizInfluence");
            return (Criteria) this;
        }

        public Criteria andBizInfluenceLike(String value) {
            addCriterion("biz_influence like", value, "bizInfluence");
            return (Criteria) this;
        }

        public Criteria andBizInfluenceNotLike(String value) {
            addCriterion("biz_influence not like", value, "bizInfluence");
            return (Criteria) this;
        }

        public Criteria andBizInfluenceIn(List<String> values) {
            addCriterion("biz_influence in", values, "bizInfluence");
            return (Criteria) this;
        }

        public Criteria andBizInfluenceNotIn(List<String> values) {
            addCriterion("biz_influence not in", values, "bizInfluence");
            return (Criteria) this;
        }

        public Criteria andBizInfluenceBetween(String value1, String value2) {
            addCriterion("biz_influence between", value1, value2, "bizInfluence");
            return (Criteria) this;
        }

        public Criteria andBizInfluenceNotBetween(String value1, String value2) {
            addCriterion("biz_influence not between", value1, value2, "bizInfluence");
            return (Criteria) this;
        }

        public Criteria andRiskDescriptionIsNull() {
            addCriterion("risk_description is null");
            return (Criteria) this;
        }

        public Criteria andRiskDescriptionIsNotNull() {
            addCriterion("risk_description is not null");
            return (Criteria) this;
        }

        public Criteria andRiskDescriptionEqualTo(String value) {
            addCriterion("risk_description =", value, "riskDescription");
            return (Criteria) this;
        }

        public Criteria andRiskDescriptionNotEqualTo(String value) {
            addCriterion("risk_description <>", value, "riskDescription");
            return (Criteria) this;
        }

        public Criteria andRiskDescriptionGreaterThan(String value) {
            addCriterion("risk_description >", value, "riskDescription");
            return (Criteria) this;
        }

        public Criteria andRiskDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("risk_description >=", value, "riskDescription");
            return (Criteria) this;
        }

        public Criteria andRiskDescriptionLessThan(String value) {
            addCriterion("risk_description <", value, "riskDescription");
            return (Criteria) this;
        }

        public Criteria andRiskDescriptionLessThanOrEqualTo(String value) {
            addCriterion("risk_description <=", value, "riskDescription");
            return (Criteria) this;
        }

        public Criteria andRiskDescriptionLike(String value) {
            addCriterion("risk_description like", value, "riskDescription");
            return (Criteria) this;
        }

        public Criteria andRiskDescriptionNotLike(String value) {
            addCriterion("risk_description not like", value, "riskDescription");
            return (Criteria) this;
        }

        public Criteria andRiskDescriptionIn(List<String> values) {
            addCriterion("risk_description in", values, "riskDescription");
            return (Criteria) this;
        }

        public Criteria andRiskDescriptionNotIn(List<String> values) {
            addCriterion("risk_description not in", values, "riskDescription");
            return (Criteria) this;
        }

        public Criteria andRiskDescriptionBetween(String value1, String value2) {
            addCriterion("risk_description between", value1, value2, "riskDescription");
            return (Criteria) this;
        }

        public Criteria andRiskDescriptionNotBetween(String value1, String value2) {
            addCriterion("risk_description not between", value1, value2, "riskDescription");
            return (Criteria) this;
        }

        public Criteria andTenantIsNull() {
            addCriterion("tenant is null");
            return (Criteria) this;
        }

        public Criteria andTenantIsNotNull() {
            addCriterion("tenant is not null");
            return (Criteria) this;
        }

        public Criteria andTenantEqualTo(String value) {
            addCriterion("tenant =", value, "tenant");
            return (Criteria) this;
        }

        public Criteria andTenantNotEqualTo(String value) {
            addCriterion("tenant <>", value, "tenant");
            return (Criteria) this;
        }

        public Criteria andTenantGreaterThan(String value) {
            addCriterion("tenant >", value, "tenant");
            return (Criteria) this;
        }

        public Criteria andTenantGreaterThanOrEqualTo(String value) {
            addCriterion("tenant >=", value, "tenant");
            return (Criteria) this;
        }

        public Criteria andTenantLessThan(String value) {
            addCriterion("tenant <", value, "tenant");
            return (Criteria) this;
        }

        public Criteria andTenantLessThanOrEqualTo(String value) {
            addCriterion("tenant <=", value, "tenant");
            return (Criteria) this;
        }

        public Criteria andTenantLike(String value) {
            addCriterion("tenant like", value, "tenant");
            return (Criteria) this;
        }

        public Criteria andTenantNotLike(String value) {
            addCriterion("tenant not like", value, "tenant");
            return (Criteria) this;
        }

        public Criteria andTenantIn(List<String> values) {
            addCriterion("tenant in", values, "tenant");
            return (Criteria) this;
        }

        public Criteria andTenantNotIn(List<String> values) {
            addCriterion("tenant not in", values, "tenant");
            return (Criteria) this;
        }

        public Criteria andTenantBetween(String value1, String value2) {
            addCriterion("tenant between", value1, value2, "tenant");
            return (Criteria) this;
        }

        public Criteria andTenantNotBetween(String value1, String value2) {
            addCriterion("tenant not between", value1, value2, "tenant");
            return (Criteria) this;
        }
    }

    /**
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends AbstractGeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue,
                String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }

    /**
     *
     * @mbg.generated
     */
    public enum OrderCondition {
        /**
         * 主键
         */
        ID("id"),
        /**
         * 创建时间
         */
        GMTCREATE("gmt_create"),
        /**
         * 修改时间
         */
        GMTMODIFIED("gmt_modified"),
        /**
         * 破网申请操作人
         */
        OPERATOR("operator"),
        /**
         * 破网申请名称
         */
        NAME("name"),
        /**
         * 破网对应的封网计划ID
         */
        BLOCKCHANGEID("blockchange_id"),
        /**
         * 破网对应的封网计划名称
         */
        BLOCKCHANGENAME("blockchange_name"),
        /**
         * 破网开始时间
         */
        STARTTIME("start_time"),
        /**
         * 破网结束时间
         */
        ENDTIME("end_time"),
        /**
         * 生效环境
         */
        EFFECTENVIRONMENT("effect_environment"),
        /**
         * 破网原因
         */
        REASONREF("reason_ref"),
        /**
         * 破网架构域范围
         */
        ARCHDOMAINRANGE("archdomain_range"),
        /**
         * 破网业务域范围
         */
        BUSGROUPRANGE("busgroup_range"),
        /**
         * 破网类型
         */
        CHANGETARGETTYPE("change_target_type"),
        /**
         * 破网对象配置
         */
        CONFIGREF("config_ref"),
        /**
         * 破网申请状态
         */
        STATUS("status"),
        /**
         * 审批流Id
         */
        APPROVALFLOWID("approval_flow_id"),
        /**
         * 破网原因类型
         */
        REASONTYPE("reason_type"),
        /**
         * 业务影响
         */
        BIZINFLUENCE("biz_influence"),
        /**
         * 风险描述和应急预案
         */
        RISKDESCRIPTION("risk_description"),
        /**
         * 站点
         */
        TENANT("tenant");

        private String columnName;

        OrderCondition(String columnName) {
            this.columnName = columnName;
        }

        public String getColumnName() {
            return columnName;
        }

        public static OrderCondition getEnumByName(String name) {
            OrderCondition[] orderConditions = OrderCondition.values();
            for (OrderCondition orderCondition : orderConditions) {
                if (orderCondition.name().equalsIgnoreCase(name)) {
                    return orderCondition;
                }
            }
            throw new RuntimeException("OrderCondition of " + name + " enum not exist");
        }

        @Override
        public String toString() {
            return columnName;
        }
    }

    /**
     *
     * @mbg.generated
     */
    public enum SortType {
        /**
         * 升序
         */
        ASC("asc"),
        /**
         * 降序
         */
        DESC("desc");

        private String value;

        SortType(String value) {
            this.value = value;
        }

        public String getValue() {
            return value;
        }

        public static SortType getEnumByName(String name) {
            SortType[] sortTypes = SortType.values();
            for (SortType sortType : sortTypes) {
                if (sortType.name().equalsIgnoreCase(name)) {
                    return sortType;
                }
            }
            throw new RuntimeException("SortType of " + name + " enum not exist");
        }

        @Override
        public String toString() {
            return value;
        }
    }
}
