/*
 * MIT License
 *
 * Copyright (c) [2023]
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package com.alipay.altershield.defender.framework.meta.dal.dataobject;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * This class was generated by Ali-Generator
 * @author xiangyue
 */
public class MetaDefenderRuleParam {
    /**
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     *
     * @mbg.generated
     */
    @Deprecated
    protected boolean distinct;

    /**
     *
     * @mbg.generated
     */
    protected boolean page;

    /**
     *
     * @mbg.generated
     */
    protected int pageIndex;

    /**
     *
     * @mbg.generated
     */
    protected int pageSize;

    /**
     *
     * @mbg.generated
     */
    protected int pageStart;

    /**
     *
     * @mbg.generated
     */
    protected String distinctSql;

    /**
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     *
     * @mbg.generated
     */
    public MetaDefenderRuleParam() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * @param orderCondition
     * @param sortType
     * @return
     *
     * @mbg.generated
     */
    public MetaDefenderRuleParam appendOrderByClause(OrderCondition orderCondition, SortType sortType) {
        if (null != orderByClause) {
            orderByClause = orderByClause + ", " + orderCondition.getColumnName() + " " + sortType.getValue();
        } else {
            orderByClause = orderCondition.getColumnName() + " " + sortType.getValue();
        }
        return this;
    }

    /**
     * @return
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * @param distinct
     *
     * @mbg.generated
     */
    @Deprecated
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * @return
     *
     * @mbg.generated
     */
    @Deprecated
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * @param page
     * @return
     *
     * @mbg.generated
     */
    public MetaDefenderRuleParam setPage(boolean page) {
        this.page = page;
        return this;
    }

    /**
     * @return
     *
     * @mbg.generated
     */
    public boolean isPage() {
        return page;
    }

    /**
     * @return
     *
     * @mbg.generated
     */
    public int getPageIndex() {
        return pageIndex;
    }

    /**
     * @param pageSize
     * @return
     *
     * @mbg.generated
     */
    public MetaDefenderRuleParam setPageSize(int pageSize) {
        this.pageSize = pageSize < 1 ? 10 : pageSize;
        this.pageIndex = pageStart < 1 ? 0 : (pageStart - 1) * this.pageSize;
        return this;
    }

    /**
     * @return
     *
     * @mbg.generated
     */
    public int getPageSize() {
        return pageSize;
    }

    /**
     * @param pageStart
     * @return
     *
     * @mbg.generated
     */
    public MetaDefenderRuleParam setPageStart(int pageStart) {
        this.pageStart = pageStart < 1 ? 1 : pageStart;
        this.pageIndex = (this.pageStart - 1) * this.pageSize;
        return this;
    }

    /**
     * @return
     *
     * @mbg.generated
     */
    public int getPageStart() {
        return pageStart;
    }

    /**
     * @param pageStart
     * @param pageSize
     *
     * @mbg.generated
     */
    public void setPagination(int pageStart, int pageSize) {
        this.page = true;
        this.pageSize = pageSize < 1 ? 10 : pageSize;
        this.pageIndex = pageStart < 1 ? 0 : (pageStart - 1) * this.pageSize;
    }

    /**
     * @param condition
     * @return
     *
     * @mbg.generated
     */
    public MetaDefenderRuleParam appendDistinct(OrderCondition condition) {
        if (null != distinctSql){
            distinctSql = distinctSql + ", " + condition.getColumnName();
        } else {
            distinctSql = condition.getColumnName();
        }
        return this;
    }

    /**
     * @return
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * @param criteria
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * @return
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * @return
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * @return
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     *
     * @mbg.generated
     */
    protected abstract static class AbstractGeneratedCriteria {
        protected List<Criterion> criteria;

        protected AbstractGeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIsNull() {
            addCriterion("gmt_create is null");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIsNotNull() {
            addCriterion("gmt_create is not null");
            return (Criteria) this;
        }

        public Criteria andGmtCreateEqualTo(Date value) {
            addCriterion("gmt_create =", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotEqualTo(Date value) {
            addCriterion("gmt_create <>", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateGreaterThan(Date value) {
            addCriterion("gmt_create >", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateGreaterThanOrEqualTo(Date value) {
            addCriterion("gmt_create >=", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateLessThan(Date value) {
            addCriterion("gmt_create <", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateLessThanOrEqualTo(Date value) {
            addCriterion("gmt_create <=", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIn(List<Date> values) {
            addCriterion("gmt_create in", values, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotIn(List<Date> values) {
            addCriterion("gmt_create not in", values, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateBetween(Date value1, Date value2) {
            addCriterion("gmt_create between", value1, value2, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotBetween(Date value1, Date value2) {
            addCriterion("gmt_create not between", value1, value2, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIsNull() {
            addCriterion("gmt_modified is null");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIsNotNull() {
            addCriterion("gmt_modified is not null");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedEqualTo(Date value) {
            addCriterion("gmt_modified =", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotEqualTo(Date value) {
            addCriterion("gmt_modified <>", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedGreaterThan(Date value) {
            addCriterion("gmt_modified >", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedGreaterThanOrEqualTo(Date value) {
            addCriterion("gmt_modified >=", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedLessThan(Date value) {
            addCriterion("gmt_modified <", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedLessThanOrEqualTo(Date value) {
            addCriterion("gmt_modified <=", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIn(List<Date> values) {
            addCriterion("gmt_modified in", values, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotIn(List<Date> values) {
            addCriterion("gmt_modified not in", values, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedBetween(Date value1, Date value2) {
            addCriterion("gmt_modified between", value1, value2, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotBetween(Date value1, Date value2) {
            addCriterion("gmt_modified not between", value1, value2, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andSuggestionIsNull() {
            addCriterion("suggestion is null");
            return (Criteria) this;
        }

        public Criteria andSuggestionIsNotNull() {
            addCriterion("suggestion is not null");
            return (Criteria) this;
        }

        public Criteria andSuggestionEqualTo(String value) {
            addCriterion("suggestion =", value, "suggestion");
            return (Criteria) this;
        }

        public Criteria andSuggestionNotEqualTo(String value) {
            addCriterion("suggestion <>", value, "suggestion");
            return (Criteria) this;
        }

        public Criteria andSuggestionGreaterThan(String value) {
            addCriterion("suggestion >", value, "suggestion");
            return (Criteria) this;
        }

        public Criteria andSuggestionGreaterThanOrEqualTo(String value) {
            addCriterion("suggestion >=", value, "suggestion");
            return (Criteria) this;
        }

        public Criteria andSuggestionLessThan(String value) {
            addCriterion("suggestion <", value, "suggestion");
            return (Criteria) this;
        }

        public Criteria andSuggestionLessThanOrEqualTo(String value) {
            addCriterion("suggestion <=", value, "suggestion");
            return (Criteria) this;
        }

        public Criteria andSuggestionLike(String value) {
            addCriterion("suggestion like", value, "suggestion");
            return (Criteria) this;
        }

        public Criteria andSuggestionNotLike(String value) {
            addCriterion("suggestion not like", value, "suggestion");
            return (Criteria) this;
        }

        public Criteria andSuggestionIn(List<String> values) {
            addCriterion("suggestion in", values, "suggestion");
            return (Criteria) this;
        }

        public Criteria andSuggestionNotIn(List<String> values) {
            addCriterion("suggestion not in", values, "suggestion");
            return (Criteria) this;
        }

        public Criteria andSuggestionBetween(String value1, String value2) {
            addCriterion("suggestion between", value1, value2, "suggestion");
            return (Criteria) this;
        }

        public Criteria andSuggestionNotBetween(String value1, String value2) {
            addCriterion("suggestion not between", value1, value2, "suggestion");
            return (Criteria) this;
        }

        public Criteria andOwnerIsNull() {
            addCriterion("owner is null");
            return (Criteria) this;
        }

        public Criteria andOwnerIsNotNull() {
            addCriterion("owner is not null");
            return (Criteria) this;
        }

        public Criteria andOwnerEqualTo(String value) {
            addCriterion("owner =", value, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerNotEqualTo(String value) {
            addCriterion("owner <>", value, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerGreaterThan(String value) {
            addCriterion("owner >", value, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerGreaterThanOrEqualTo(String value) {
            addCriterion("owner >=", value, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerLessThan(String value) {
            addCriterion("owner <", value, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerLessThanOrEqualTo(String value) {
            addCriterion("owner <=", value, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerLike(String value) {
            addCriterion("owner like", value, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerNotLike(String value) {
            addCriterion("owner not like", value, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerIn(List<String> values) {
            addCriterion("owner in", values, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerNotIn(List<String> values) {
            addCriterion("owner not in", values, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerBetween(String value1, String value2) {
            addCriterion("owner between", value1, value2, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerNotBetween(String value1, String value2) {
            addCriterion("owner not between", value1, value2, "owner");
            return (Criteria) this;
        }

        public Criteria andStageIsNull() {
            addCriterion("stage is null");
            return (Criteria) this;
        }

        public Criteria andStageIsNotNull() {
            addCriterion("stage is not null");
            return (Criteria) this;
        }

        public Criteria andStageEqualTo(String value) {
            addCriterion("stage =", value, "stage");
            return (Criteria) this;
        }

        public Criteria andStageNotEqualTo(String value) {
            addCriterion("stage <>", value, "stage");
            return (Criteria) this;
        }

        public Criteria andStageGreaterThan(String value) {
            addCriterion("stage >", value, "stage");
            return (Criteria) this;
        }

        public Criteria andStageGreaterThanOrEqualTo(String value) {
            addCriterion("stage >=", value, "stage");
            return (Criteria) this;
        }

        public Criteria andStageLessThan(String value) {
            addCriterion("stage <", value, "stage");
            return (Criteria) this;
        }

        public Criteria andStageLessThanOrEqualTo(String value) {
            addCriterion("stage <=", value, "stage");
            return (Criteria) this;
        }

        public Criteria andStageLike(String value) {
            addCriterion("stage like", value, "stage");
            return (Criteria) this;
        }

        public Criteria andStageNotLike(String value) {
            addCriterion("stage not like", value, "stage");
            return (Criteria) this;
        }

        public Criteria andStageIn(List<String> values) {
            addCriterion("stage in", values, "stage");
            return (Criteria) this;
        }

        public Criteria andStageNotIn(List<String> values) {
            addCriterion("stage not in", values, "stage");
            return (Criteria) this;
        }

        public Criteria andStageBetween(String value1, String value2) {
            addCriterion("stage between", value1, value2, "stage");
            return (Criteria) this;
        }

        public Criteria andStageNotBetween(String value1, String value2) {
            addCriterion("stage not between", value1, value2, "stage");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("status like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("status not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andExceptionStrategyIsNull() {
            addCriterion("exception_strategy is null");
            return (Criteria) this;
        }

        public Criteria andExceptionStrategyIsNotNull() {
            addCriterion("exception_strategy is not null");
            return (Criteria) this;
        }

        public Criteria andExceptionStrategyEqualTo(String value) {
            addCriterion("exception_strategy =", value, "exceptionStrategy");
            return (Criteria) this;
        }

        public Criteria andExceptionStrategyNotEqualTo(String value) {
            addCriterion("exception_strategy <>", value, "exceptionStrategy");
            return (Criteria) this;
        }

        public Criteria andExceptionStrategyGreaterThan(String value) {
            addCriterion("exception_strategy >", value, "exceptionStrategy");
            return (Criteria) this;
        }

        public Criteria andExceptionStrategyGreaterThanOrEqualTo(String value) {
            addCriterion("exception_strategy >=", value, "exceptionStrategy");
            return (Criteria) this;
        }

        public Criteria andExceptionStrategyLessThan(String value) {
            addCriterion("exception_strategy <", value, "exceptionStrategy");
            return (Criteria) this;
        }

        public Criteria andExceptionStrategyLessThanOrEqualTo(String value) {
            addCriterion("exception_strategy <=", value, "exceptionStrategy");
            return (Criteria) this;
        }

        public Criteria andExceptionStrategyLike(String value) {
            addCriterion("exception_strategy like", value, "exceptionStrategy");
            return (Criteria) this;
        }

        public Criteria andExceptionStrategyNotLike(String value) {
            addCriterion("exception_strategy not like", value, "exceptionStrategy");
            return (Criteria) this;
        }

        public Criteria andExceptionStrategyIn(List<String> values) {
            addCriterion("exception_strategy in", values, "exceptionStrategy");
            return (Criteria) this;
        }

        public Criteria andExceptionStrategyNotIn(List<String> values) {
            addCriterion("exception_strategy not in", values, "exceptionStrategy");
            return (Criteria) this;
        }

        public Criteria andExceptionStrategyBetween(String value1, String value2) {
            addCriterion("exception_strategy between", value1, value2, "exceptionStrategy");
            return (Criteria) this;
        }

        public Criteria andExceptionStrategyNotBetween(String value1, String value2) {
            addCriterion("exception_strategy not between", value1, value2, "exceptionStrategy");
            return (Criteria) this;
        }

        public Criteria andDefenseRangeTypeIsNull() {
            addCriterion("defense_range_type is null");
            return (Criteria) this;
        }

        public Criteria andDefenseRangeTypeIsNotNull() {
            addCriterion("defense_range_type is not null");
            return (Criteria) this;
        }

        public Criteria andDefenseRangeTypeEqualTo(String value) {
            addCriterion("defense_range_type =", value, "defenseRangeType");
            return (Criteria) this;
        }

        public Criteria andDefenseRangeTypeNotEqualTo(String value) {
            addCriterion("defense_range_type <>", value, "defenseRangeType");
            return (Criteria) this;
        }

        public Criteria andDefenseRangeTypeGreaterThan(String value) {
            addCriterion("defense_range_type >", value, "defenseRangeType");
            return (Criteria) this;
        }

        public Criteria andDefenseRangeTypeGreaterThanOrEqualTo(String value) {
            addCriterion("defense_range_type >=", value, "defenseRangeType");
            return (Criteria) this;
        }

        public Criteria andDefenseRangeTypeLessThan(String value) {
            addCriterion("defense_range_type <", value, "defenseRangeType");
            return (Criteria) this;
        }

        public Criteria andDefenseRangeTypeLessThanOrEqualTo(String value) {
            addCriterion("defense_range_type <=", value, "defenseRangeType");
            return (Criteria) this;
        }

        public Criteria andDefenseRangeTypeLike(String value) {
            addCriterion("defense_range_type like", value, "defenseRangeType");
            return (Criteria) this;
        }

        public Criteria andDefenseRangeTypeNotLike(String value) {
            addCriterion("defense_range_type not like", value, "defenseRangeType");
            return (Criteria) this;
        }

        public Criteria andDefenseRangeTypeIn(List<String> values) {
            addCriterion("defense_range_type in", values, "defenseRangeType");
            return (Criteria) this;
        }

        public Criteria andDefenseRangeTypeNotIn(List<String> values) {
            addCriterion("defense_range_type not in", values, "defenseRangeType");
            return (Criteria) this;
        }

        public Criteria andDefenseRangeTypeBetween(String value1, String value2) {
            addCriterion("defense_range_type between", value1, value2, "defenseRangeType");
            return (Criteria) this;
        }

        public Criteria andDefenseRangeTypeNotBetween(String value1, String value2) {
            addCriterion("defense_range_type not between", value1, value2, "defenseRangeType");
            return (Criteria) this;
        }

        public Criteria andDefenseRangeKeyIsNull() {
            addCriterion("defense_range_key is null");
            return (Criteria) this;
        }

        public Criteria andDefenseRangeKeyIsNotNull() {
            addCriterion("defense_range_key is not null");
            return (Criteria) this;
        }

        public Criteria andDefenseRangeKeyEqualTo(String value) {
            addCriterion("defense_range_key =", value, "defenseRangeKey");
            return (Criteria) this;
        }

        public Criteria andDefenseRangeKeyNotEqualTo(String value) {
            addCriterion("defense_range_key <>", value, "defenseRangeKey");
            return (Criteria) this;
        }

        public Criteria andDefenseRangeKeyGreaterThan(String value) {
            addCriterion("defense_range_key >", value, "defenseRangeKey");
            return (Criteria) this;
        }

        public Criteria andDefenseRangeKeyGreaterThanOrEqualTo(String value) {
            addCriterion("defense_range_key >=", value, "defenseRangeKey");
            return (Criteria) this;
        }

        public Criteria andDefenseRangeKeyLessThan(String value) {
            addCriterion("defense_range_key <", value, "defenseRangeKey");
            return (Criteria) this;
        }

        public Criteria andDefenseRangeKeyLessThanOrEqualTo(String value) {
            addCriterion("defense_range_key <=", value, "defenseRangeKey");
            return (Criteria) this;
        }

        public Criteria andDefenseRangeKeyLike(String value) {
            addCriterion("defense_range_key like", value, "defenseRangeKey");
            return (Criteria) this;
        }

        public Criteria andDefenseRangeKeyNotLike(String value) {
            addCriterion("defense_range_key not like", value, "defenseRangeKey");
            return (Criteria) this;
        }

        public Criteria andDefenseRangeKeyIn(List<String> values) {
            addCriterion("defense_range_key in", values, "defenseRangeKey");
            return (Criteria) this;
        }

        public Criteria andDefenseRangeKeyNotIn(List<String> values) {
            addCriterion("defense_range_key not in", values, "defenseRangeKey");
            return (Criteria) this;
        }

        public Criteria andDefenseRangeKeyBetween(String value1, String value2) {
            addCriterion("defense_range_key between", value1, value2, "defenseRangeKey");
            return (Criteria) this;
        }

        public Criteria andDefenseRangeKeyNotBetween(String value1, String value2) {
            addCriterion("defense_range_key not between", value1, value2, "defenseRangeKey");
            return (Criteria) this;
        }

        public Criteria andExternalIdIsNull() {
            addCriterion("external_id is null");
            return (Criteria) this;
        }

        public Criteria andExternalIdIsNotNull() {
            addCriterion("external_id is not null");
            return (Criteria) this;
        }

        public Criteria andExternalIdEqualTo(String value) {
            addCriterion("external_id =", value, "externalId");
            return (Criteria) this;
        }

        public Criteria andExternalIdNotEqualTo(String value) {
            addCriterion("external_id <>", value, "externalId");
            return (Criteria) this;
        }

        public Criteria andExternalIdGreaterThan(String value) {
            addCriterion("external_id >", value, "externalId");
            return (Criteria) this;
        }

        public Criteria andExternalIdGreaterThanOrEqualTo(String value) {
            addCriterion("external_id >=", value, "externalId");
            return (Criteria) this;
        }

        public Criteria andExternalIdLessThan(String value) {
            addCriterion("external_id <", value, "externalId");
            return (Criteria) this;
        }

        public Criteria andExternalIdLessThanOrEqualTo(String value) {
            addCriterion("external_id <=", value, "externalId");
            return (Criteria) this;
        }

        public Criteria andExternalIdLike(String value) {
            addCriterion("external_id like", value, "externalId");
            return (Criteria) this;
        }

        public Criteria andExternalIdNotLike(String value) {
            addCriterion("external_id not like", value, "externalId");
            return (Criteria) this;
        }

        public Criteria andExternalIdIn(List<String> values) {
            addCriterion("external_id in", values, "externalId");
            return (Criteria) this;
        }

        public Criteria andExternalIdNotIn(List<String> values) {
            addCriterion("external_id not in", values, "externalId");
            return (Criteria) this;
        }

        public Criteria andExternalIdBetween(String value1, String value2) {
            addCriterion("external_id between", value1, value2, "externalId");
            return (Criteria) this;
        }

        public Criteria andExternalIdNotBetween(String value1, String value2) {
            addCriterion("external_id not between", value1, value2, "externalId");
            return (Criteria) this;
        }

        public Criteria andTenantIsNull() {
            addCriterion("tenant is null");
            return (Criteria) this;
        }

        public Criteria andTenantIsNotNull() {
            addCriterion("tenant is not null");
            return (Criteria) this;
        }

        public Criteria andTenantEqualTo(String value) {
            addCriterion("tenant =", value, "tenant");
            return (Criteria) this;
        }

        public Criteria andTenantNotEqualTo(String value) {
            addCriterion("tenant <>", value, "tenant");
            return (Criteria) this;
        }

        public Criteria andTenantGreaterThan(String value) {
            addCriterion("tenant >", value, "tenant");
            return (Criteria) this;
        }

        public Criteria andTenantGreaterThanOrEqualTo(String value) {
            addCriterion("tenant >=", value, "tenant");
            return (Criteria) this;
        }

        public Criteria andTenantLessThan(String value) {
            addCriterion("tenant <", value, "tenant");
            return (Criteria) this;
        }

        public Criteria andTenantLessThanOrEqualTo(String value) {
            addCriterion("tenant <=", value, "tenant");
            return (Criteria) this;
        }

        public Criteria andTenantLike(String value) {
            addCriterion("tenant like", value, "tenant");
            return (Criteria) this;
        }

        public Criteria andTenantNotLike(String value) {
            addCriterion("tenant not like", value, "tenant");
            return (Criteria) this;
        }

        public Criteria andTenantIn(List<String> values) {
            addCriterion("tenant in", values, "tenant");
            return (Criteria) this;
        }

        public Criteria andTenantNotIn(List<String> values) {
            addCriterion("tenant not in", values, "tenant");
            return (Criteria) this;
        }

        public Criteria andTenantBetween(String value1, String value2) {
            addCriterion("tenant between", value1, value2, "tenant");
            return (Criteria) this;
        }

        public Criteria andTenantNotBetween(String value1, String value2) {
            addCriterion("tenant not between", value1, value2, "tenant");
            return (Criteria) this;
        }

        public Criteria andDelaySecondIsNull() {
            addCriterion("delay_second is null");
            return (Criteria) this;
        }

        public Criteria andDelaySecondIsNotNull() {
            addCriterion("delay_second is not null");
            return (Criteria) this;
        }

        public Criteria andDelaySecondEqualTo(Integer value) {
            addCriterion("delay_second =", value, "delaySecond");
            return (Criteria) this;
        }

        public Criteria andDelaySecondNotEqualTo(Integer value) {
            addCriterion("delay_second <>", value, "delaySecond");
            return (Criteria) this;
        }

        public Criteria andDelaySecondGreaterThan(Integer value) {
            addCriterion("delay_second >", value, "delaySecond");
            return (Criteria) this;
        }

        public Criteria andDelaySecondGreaterThanOrEqualTo(Integer value) {
            addCriterion("delay_second >=", value, "delaySecond");
            return (Criteria) this;
        }

        public Criteria andDelaySecondLessThan(Integer value) {
            addCriterion("delay_second <", value, "delaySecond");
            return (Criteria) this;
        }

        public Criteria andDelaySecondLessThanOrEqualTo(Integer value) {
            addCriterion("delay_second <=", value, "delaySecond");
            return (Criteria) this;
        }

        public Criteria andDelaySecondIn(List<Integer> values) {
            addCriterion("delay_second in", values, "delaySecond");
            return (Criteria) this;
        }

        public Criteria andDelaySecondNotIn(List<Integer> values) {
            addCriterion("delay_second not in", values, "delaySecond");
            return (Criteria) this;
        }

        public Criteria andDelaySecondBetween(Integer value1, Integer value2) {
            addCriterion("delay_second between", value1, value2, "delaySecond");
            return (Criteria) this;
        }

        public Criteria andDelaySecondNotBetween(Integer value1, Integer value2) {
            addCriterion("delay_second not between", value1, value2, "delaySecond");
            return (Criteria) this;
        }

        public Criteria andPluginKeyIsNull() {
            addCriterion("plugin_key is null");
            return (Criteria) this;
        }

        public Criteria andPluginKeyIsNotNull() {
            addCriterion("plugin_key is not null");
            return (Criteria) this;
        }

        public Criteria andPluginKeyEqualTo(String value) {
            addCriterion("plugin_key =", value, "pluginKey");
            return (Criteria) this;
        }

        public Criteria andPluginKeyNotEqualTo(String value) {
            addCriterion("plugin_key <>", value, "pluginKey");
            return (Criteria) this;
        }

        public Criteria andPluginKeyGreaterThan(String value) {
            addCriterion("plugin_key >", value, "pluginKey");
            return (Criteria) this;
        }

        public Criteria andPluginKeyGreaterThanOrEqualTo(String value) {
            addCriterion("plugin_key >=", value, "pluginKey");
            return (Criteria) this;
        }

        public Criteria andPluginKeyLessThan(String value) {
            addCriterion("plugin_key <", value, "pluginKey");
            return (Criteria) this;
        }

        public Criteria andPluginKeyLessThanOrEqualTo(String value) {
            addCriterion("plugin_key <=", value, "pluginKey");
            return (Criteria) this;
        }

        public Criteria andPluginKeyLike(String value) {
            addCriterion("plugin_key like", value, "pluginKey");
            return (Criteria) this;
        }

        public Criteria andPluginKeyNotLike(String value) {
            addCriterion("plugin_key not like", value, "pluginKey");
            return (Criteria) this;
        }

        public Criteria andPluginKeyIn(List<String> values) {
            addCriterion("plugin_key in", values, "pluginKey");
            return (Criteria) this;
        }

        public Criteria andPluginKeyNotIn(List<String> values) {
            addCriterion("plugin_key not in", values, "pluginKey");
            return (Criteria) this;
        }

        public Criteria andPluginKeyBetween(String value1, String value2) {
            addCriterion("plugin_key between", value1, value2, "pluginKey");
            return (Criteria) this;
        }

        public Criteria andPluginKeyNotBetween(String value1, String value2) {
            addCriterion("plugin_key not between", value1, value2, "pluginKey");
            return (Criteria) this;
        }

        public Criteria andMainClassIsNull() {
            addCriterion("main_class is null");
            return (Criteria) this;
        }

        public Criteria andMainClassIsNotNull() {
            addCriterion("main_class is not null");
            return (Criteria) this;
        }

        public Criteria andMainClassEqualTo(String value) {
            addCriterion("main_class =", value, "mainClass");
            return (Criteria) this;
        }

        public Criteria andMainClassNotEqualTo(String value) {
            addCriterion("main_class <>", value, "mainClass");
            return (Criteria) this;
        }

        public Criteria andMainClassGreaterThan(String value) {
            addCriterion("main_class >", value, "mainClass");
            return (Criteria) this;
        }

        public Criteria andMainClassGreaterThanOrEqualTo(String value) {
            addCriterion("main_class >=", value, "mainClass");
            return (Criteria) this;
        }

        public Criteria andMainClassLessThan(String value) {
            addCriterion("main_class <", value, "mainClass");
            return (Criteria) this;
        }

        public Criteria andMainClassLessThanOrEqualTo(String value) {
            addCriterion("main_class <=", value, "mainClass");
            return (Criteria) this;
        }

        public Criteria andMainClassLike(String value) {
            addCriterion("main_class like", value, "mainClass");
            return (Criteria) this;
        }

        public Criteria andMainClassNotLike(String value) {
            addCriterion("main_class not like", value, "mainClass");
            return (Criteria) this;
        }

        public Criteria andMainClassIn(List<String> values) {
            addCriterion("main_class in", values, "mainClass");
            return (Criteria) this;
        }

        public Criteria andMainClassNotIn(List<String> values) {
            addCriterion("main_class not in", values, "mainClass");
            return (Criteria) this;
        }

        public Criteria andMainClassBetween(String value1, String value2) {
            addCriterion("main_class between", value1, value2, "mainClass");
            return (Criteria) this;
        }

        public Criteria andMainClassNotBetween(String value1, String value2) {
            addCriterion("main_class not between", value1, value2, "mainClass");
            return (Criteria) this;
        }

        public Criteria andPluginInvokeTypeIsNull() {
            addCriterion("plugin_invoke_type is null");
            return (Criteria) this;
        }

        public Criteria andPluginInvokeTypeIsNotNull() {
            addCriterion("plugin_invoke_type is not null");
            return (Criteria) this;
        }

        public Criteria andPluginInvokeTypeEqualTo(String value) {
            addCriterion("plugin_invoke_type =", value, "pluginInvokeType");
            return (Criteria) this;
        }

        public Criteria andPluginInvokeTypeNotEqualTo(String value) {
            addCriterion("plugin_invoke_type <>", value, "pluginInvokeType");
            return (Criteria) this;
        }

        public Criteria andPluginInvokeTypeGreaterThan(String value) {
            addCriterion("plugin_invoke_type >", value, "pluginInvokeType");
            return (Criteria) this;
        }

        public Criteria andPluginInvokeTypeGreaterThanOrEqualTo(String value) {
            addCriterion("plugin_invoke_type >=", value, "pluginInvokeType");
            return (Criteria) this;
        }

        public Criteria andPluginInvokeTypeLessThan(String value) {
            addCriterion("plugin_invoke_type <", value, "pluginInvokeType");
            return (Criteria) this;
        }

        public Criteria andPluginInvokeTypeLessThanOrEqualTo(String value) {
            addCriterion("plugin_invoke_type <=", value, "pluginInvokeType");
            return (Criteria) this;
        }

        public Criteria andPluginInvokeTypeLike(String value) {
            addCriterion("plugin_invoke_type like", value, "pluginInvokeType");
            return (Criteria) this;
        }

        public Criteria andPluginInvokeTypeNotLike(String value) {
            addCriterion("plugin_invoke_type not like", value, "pluginInvokeType");
            return (Criteria) this;
        }

        public Criteria andPluginInvokeTypeIn(List<String> values) {
            addCriterion("plugin_invoke_type in", values, "pluginInvokeType");
            return (Criteria) this;
        }

        public Criteria andPluginInvokeTypeNotIn(List<String> values) {
            addCriterion("plugin_invoke_type not in", values, "pluginInvokeType");
            return (Criteria) this;
        }

        public Criteria andPluginInvokeTypeBetween(String value1, String value2) {
            addCriterion("plugin_invoke_type between", value1, value2, "pluginInvokeType");
            return (Criteria) this;
        }

        public Criteria andPluginInvokeTypeNotBetween(String value1, String value2) {
            addCriterion("plugin_invoke_type not between", value1, value2, "pluginInvokeType");
            return (Criteria) this;
        }

        public Criteria andIgnoreTagIsNull() {
            addCriterion("ignore_tag is null");
            return (Criteria) this;
        }

        public Criteria andIgnoreTagIsNotNull() {
            addCriterion("ignore_tag is not null");
            return (Criteria) this;
        }

        public Criteria andIgnoreTagEqualTo(String value) {
            addCriterion("ignore_tag =", value, "ignoreTag");
            return (Criteria) this;
        }

        public Criteria andIgnoreTagNotEqualTo(String value) {
            addCriterion("ignore_tag <>", value, "ignoreTag");
            return (Criteria) this;
        }

        public Criteria andIgnoreTagGreaterThan(String value) {
            addCriterion("ignore_tag >", value, "ignoreTag");
            return (Criteria) this;
        }

        public Criteria andIgnoreTagGreaterThanOrEqualTo(String value) {
            addCriterion("ignore_tag >=", value, "ignoreTag");
            return (Criteria) this;
        }

        public Criteria andIgnoreTagLessThan(String value) {
            addCriterion("ignore_tag <", value, "ignoreTag");
            return (Criteria) this;
        }

        public Criteria andIgnoreTagLessThanOrEqualTo(String value) {
            addCriterion("ignore_tag <=", value, "ignoreTag");
            return (Criteria) this;
        }

        public Criteria andIgnoreTagLike(String value) {
            addCriterion("ignore_tag like", value, "ignoreTag");
            return (Criteria) this;
        }

        public Criteria andIgnoreTagNotLike(String value) {
            addCriterion("ignore_tag not like", value, "ignoreTag");
            return (Criteria) this;
        }

        public Criteria andIgnoreTagIn(List<String> values) {
            addCriterion("ignore_tag in", values, "ignoreTag");
            return (Criteria) this;
        }

        public Criteria andIgnoreTagNotIn(List<String> values) {
            addCriterion("ignore_tag not in", values, "ignoreTag");
            return (Criteria) this;
        }

        public Criteria andIgnoreTagBetween(String value1, String value2) {
            addCriterion("ignore_tag between", value1, value2, "ignoreTag");
            return (Criteria) this;
        }

        public Criteria andIgnoreTagNotBetween(String value1, String value2) {
            addCriterion("ignore_tag not between", value1, value2, "ignoreTag");
            return (Criteria) this;
        }

        public Criteria andMaxDetectSecondIsNull() {
            addCriterion("max_detect_second is null");
            return (Criteria) this;
        }

        public Criteria andMaxDetectSecondIsNotNull() {
            addCriterion("max_detect_second is not null");
            return (Criteria) this;
        }

        public Criteria andMaxDetectSecondEqualTo(Integer value) {
            addCriterion("max_detect_second =", value, "maxDetectSecond");
            return (Criteria) this;
        }

        public Criteria andMaxDetectSecondNotEqualTo(Integer value) {
            addCriterion("max_detect_second <>", value, "maxDetectSecond");
            return (Criteria) this;
        }

        public Criteria andMaxDetectSecondGreaterThan(Integer value) {
            addCriterion("max_detect_second >", value, "maxDetectSecond");
            return (Criteria) this;
        }

        public Criteria andMaxDetectSecondGreaterThanOrEqualTo(Integer value) {
            addCriterion("max_detect_second >=", value, "maxDetectSecond");
            return (Criteria) this;
        }

        public Criteria andMaxDetectSecondLessThan(Integer value) {
            addCriterion("max_detect_second <", value, "maxDetectSecond");
            return (Criteria) this;
        }

        public Criteria andMaxDetectSecondLessThanOrEqualTo(Integer value) {
            addCriterion("max_detect_second <=", value, "maxDetectSecond");
            return (Criteria) this;
        }

        public Criteria andMaxDetectSecondIn(List<Integer> values) {
            addCriterion("max_detect_second in", values, "maxDetectSecond");
            return (Criteria) this;
        }

        public Criteria andMaxDetectSecondNotIn(List<Integer> values) {
            addCriterion("max_detect_second not in", values, "maxDetectSecond");
            return (Criteria) this;
        }

        public Criteria andMaxDetectSecondBetween(Integer value1, Integer value2) {
            addCriterion("max_detect_second between", value1, value2, "maxDetectSecond");
            return (Criteria) this;
        }

        public Criteria andMaxDetectSecondNotBetween(Integer value1, Integer value2) {
            addCriterion("max_detect_second not between", value1, value2, "maxDetectSecond");
            return (Criteria) this;
        }

        public Criteria andArgRefIsNull() {
            addCriterion("arg_ref is null");
            return (Criteria) this;
        }

        public Criteria andArgRefIsNotNull() {
            addCriterion("arg_ref is not null");
            return (Criteria) this;
        }

        public Criteria andArgRefEqualTo(String value) {
            addCriterion("arg_ref =", value, "argRef");
            return (Criteria) this;
        }

        public Criteria andArgRefNotEqualTo(String value) {
            addCriterion("arg_ref <>", value, "argRef");
            return (Criteria) this;
        }

        public Criteria andArgRefGreaterThan(String value) {
            addCriterion("arg_ref >", value, "argRef");
            return (Criteria) this;
        }

        public Criteria andArgRefGreaterThanOrEqualTo(String value) {
            addCriterion("arg_ref >=", value, "argRef");
            return (Criteria) this;
        }

        public Criteria andArgRefLessThan(String value) {
            addCriterion("arg_ref <", value, "argRef");
            return (Criteria) this;
        }

        public Criteria andArgRefLessThanOrEqualTo(String value) {
            addCriterion("arg_ref <=", value, "argRef");
            return (Criteria) this;
        }

        public Criteria andArgRefLike(String value) {
            addCriterion("arg_ref like", value, "argRef");
            return (Criteria) this;
        }

        public Criteria andArgRefNotLike(String value) {
            addCriterion("arg_ref not like", value, "argRef");
            return (Criteria) this;
        }

        public Criteria andArgRefIn(List<String> values) {
            addCriterion("arg_ref in", values, "argRef");
            return (Criteria) this;
        }

        public Criteria andArgRefNotIn(List<String> values) {
            addCriterion("arg_ref not in", values, "argRef");
            return (Criteria) this;
        }

        public Criteria andArgRefBetween(String value1, String value2) {
            addCriterion("arg_ref between", value1, value2, "argRef");
            return (Criteria) this;
        }

        public Criteria andArgRefNotBetween(String value1, String value2) {
            addCriterion("arg_ref not between", value1, value2, "argRef");
            return (Criteria) this;
        }

        public Criteria andChangeFilterRefIsNull() {
            addCriterion("change_filter_ref is null");
            return (Criteria) this;
        }

        public Criteria andChangeFilterRefIsNotNull() {
            addCriterion("change_filter_ref is not null");
            return (Criteria) this;
        }

        public Criteria andChangeFilterRefEqualTo(String value) {
            addCriterion("change_filter_ref =", value, "changeFilterRef");
            return (Criteria) this;
        }

        public Criteria andChangeFilterRefNotEqualTo(String value) {
            addCriterion("change_filter_ref <>", value, "changeFilterRef");
            return (Criteria) this;
        }

        public Criteria andChangeFilterRefGreaterThan(String value) {
            addCriterion("change_filter_ref >", value, "changeFilterRef");
            return (Criteria) this;
        }

        public Criteria andChangeFilterRefGreaterThanOrEqualTo(String value) {
            addCriterion("change_filter_ref >=", value, "changeFilterRef");
            return (Criteria) this;
        }

        public Criteria andChangeFilterRefLessThan(String value) {
            addCriterion("change_filter_ref <", value, "changeFilterRef");
            return (Criteria) this;
        }

        public Criteria andChangeFilterRefLessThanOrEqualTo(String value) {
            addCriterion("change_filter_ref <=", value, "changeFilterRef");
            return (Criteria) this;
        }

        public Criteria andChangeFilterRefLike(String value) {
            addCriterion("change_filter_ref like", value, "changeFilterRef");
            return (Criteria) this;
        }

        public Criteria andChangeFilterRefNotLike(String value) {
            addCriterion("change_filter_ref not like", value, "changeFilterRef");
            return (Criteria) this;
        }

        public Criteria andChangeFilterRefIn(List<String> values) {
            addCriterion("change_filter_ref in", values, "changeFilterRef");
            return (Criteria) this;
        }

        public Criteria andChangeFilterRefNotIn(List<String> values) {
            addCriterion("change_filter_ref not in", values, "changeFilterRef");
            return (Criteria) this;
        }

        public Criteria andChangeFilterRefBetween(String value1, String value2) {
            addCriterion("change_filter_ref between", value1, value2, "changeFilterRef");
            return (Criteria) this;
        }

        public Criteria andChangeFilterRefNotBetween(String value1, String value2) {
            addCriterion("change_filter_ref not between", value1, value2, "changeFilterRef");
            return (Criteria) this;
        }
    }

    /**
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends AbstractGeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }

    /**
     *
     * @mbg.generated
     */
    public enum OrderCondition {
        /**
         *The primary key
         */
        ID("id"),
        /**
         *Create time
         */
        GMTCREATE("gmt_create"),
        /**
         *Last modify time
         */
        GMTMODIFIED("gmt_modified"),
        /**
         *Rule name
         */
        NAME("name"),
        /**
         *Handling suggestions
         */
        SUGGESTION("suggestion"),
        /**
         *Defense rule administrator, multiple commas separated
         */
        OWNER("owner"),
        /**
         *Pre or post
         */
        STAGE("stage"),
        /**
         *Defense rule status-closed/in effect/trial running
         */
        STATUS("status"),
        /**
         *Rule exception handling strategy - intercept changes/release changes
         */
        EXCEPTIONSTRATEGY("exception_strategy"),
        /**
         *Defense range type
         */
        DEFENSERANGETYPE("defense_range_type"),
        /**
         *Defense range key
         */
        DEFENSERANGEKEY("defense_range_key"),
        /**
         *Associated downstream platform rule id, optional
         */
        EXTERNALID("external_id"),
        /**
         *Tenant to which defense rules belong
         */
        TENANT("tenant"),
        /**
         *Delayed execution time, unit: seconds
         */
        DELAYSECOND("delay_second"),
        /**
         *Plugin key used by defense rules
         */
        PLUGINKEY("plugin_key"),
        /**
         *Main class of plugin used by defense rules
         */
        MAINCLASS("main_class"),
        /**
         *Plugin call type: synchronous, asynchronous
         */
        PLUGININVOKETYPE("plugin_invoke_type"),
        /**
         *Ignore permissions: IGNORE directly ignores, NOT ALLOW prohibits ignoring
         */
        IGNORETAG("ignore_tag"),
        /**
         *The maximum detect time, when pre check, is the forward detect time. Unit: seconds
         */
        MAXDETECTSECOND("max_detect_second"),
        /**
         *Defense rule parameter configuration
         */
        ARGREF("arg_ref"),
        /**
         *Defense rule filter conditions
         */
        CHANGEFILTERREF("change_filter_ref");

        private String columnName;

        OrderCondition(String columnName) {
            this.columnName = columnName;
        }

        public String getColumnName() {
            return columnName;
        }

        public static OrderCondition getEnumByName(String name) {
            OrderCondition[] orderConditions = OrderCondition.values();
            for (OrderCondition orderCondition : orderConditions) {
                if (orderCondition.name().equalsIgnoreCase(name)) {
                    return orderCondition;
                }
            }
            throw new RuntimeException("OrderCondition of " + name + " enum not exist");
        }

        @Override
        public String toString() {
            return columnName;
        }
    }

    /**
     *
     * @mbg.generated
     */
    public enum SortType {
        /**
         * 升序
         */
        ASC("asc"),
        /**
         * 降序
         */
        DESC("desc");

        private String value;

        SortType(String value) {
            this.value = value;
        }

        public String getValue() {
            return value;
        }

        public static SortType getEnumByName(String name) {
            SortType[] sortTypes = SortType.values();
            for (SortType sortType : sortTypes) {
                if (sortType.name().equalsIgnoreCase(name)) {
                    return sortType;
                }
            }
            throw new RuntimeException("SortType of " + name + " enum not exist");
        }

        @Override
        public String toString() {
            return value;
        }
    }
}