/*
 * MIT License
 *
 * Copyright (c) [2023]
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
//package com.alipay.altershield.defender.changewindow.dal.mapper;
//
//import com.alipay.opscloud.changewindow.dal.dataobject.OpscldMetaReleaseChangeDO;
//import com.alipay.opscloud.changewindow.dal.dataobject.OpscldMetaReleasechangeParam;
//import org.apache.ibatis.annotations.Mapper;
//import org.apache.ibatis.annotations.Param;
//
//import java.util.List;
//
///**
// * This class was generated by Ali-Generator
// * @author shengzhang
// */
//@Mapper
//public interface OpscldMetaReleasechangeMapper {
//    /**
//     * @param opscldMetaReleasechangeParam
//     * @return
//     *
//     * @mbg.generated
//     */
//    long countByParam(OpscldMetaReleasechangeParam opscldMetaReleasechangeParam);
//
//    /**
//     * @param opscldMetaReleasechangeParam
//     * @return
//     *
//     * @mbg.generated
//     */
//    int deleteByParam(OpscldMetaReleasechangeParam opscldMetaReleasechangeParam);
//
//    /**
//     * @param id
//     * @return
//     *
//     * @mbg.generated
//     */
//    int deleteByPrimaryKey(String id);
//
//    /**
//     * @param record
//     * @return
//     *
//     * @mbg.generated
//     */
//    int insert(OpscldMetaReleaseChangeDO record);
//
//    /**
//     * @param record
//     * @return
//     *
//     * @mbg.generated
//     */
//    int insertSelective(OpscldMetaReleaseChangeDO record);
//
//    /**
//     * @param opscldMetaReleasechangeParam
//     * @return
//     *
//     * @mbg.generated
//     */
//    List<OpscldMetaReleaseChangeDO> selectByParam(OpscldMetaReleasechangeParam opscldMetaReleasechangeParam);
//
//    /**
//     * @param id
//     * @return
//     *
//     * @mbg.generated
//     */
//    OpscldMetaReleaseChangeDO selectByPrimaryKey(String id);
//
//    /**
//     * @param record
//     * @param opscldMetaReleasechangeParam
//     * @return
//     *
//     * @mbg.generated
//     */
//    int updateByParamSelective(@Param("record") OpscldMetaReleaseChangeDO record, @Param("opscldMetaReleasechangeParam") OpscldMetaReleasechangeParam opscldMetaReleasechangeParam);
//
//    /**
//     * @param record
//     * @param opscldMetaReleasechangeParam
//     * @return
//     *
//     * @mbg.generated
//     */
//    int updateByParam(@Param("record") OpscldMetaReleaseChangeDO record, @Param("opscldMetaReleasechangeParam") OpscldMetaReleasechangeParam opscldMetaReleasechangeParam);
//
//    /**
//     * @param record
//     * @return
//     *
//     * @mbg.generated
//     */
//    int updateByPrimaryKeySelective(OpscldMetaReleaseChangeDO record);
//
//    /**
//     * @param record
//     * @return
//     *
//     * @mbg.generated
//     */
//    int updateByPrimaryKey(OpscldMetaReleaseChangeDO record);
//
//    /**
//     * @param records
//     * @return
//     *
//     * @mbg.generated
//     */
//    int batchInsert(List<OpscldMetaReleaseChangeDO> records);
//}